### ISSUE TITLE
[Aula 02] .gitignore parte 3

### ISSUE THREAD

**Issue by theandersonn** [da2k/curso-git-e-github-ninja#1]
@fdaciuk No vídeo Aula 2 parte 3 fica sem som a aprtir de 01:50.

Eu tenho uma dúvida sobre o arquivo .gitignore para WordPress, segue exemplo do odin:
https://github.com/wpbrasil/odin/blob/master/.gitignore

O que significa? 
# Global

._*
.AppleDouble
.DS_Store
.localized
.LSOverride
.Spotlight-V100
.Trashes
Icon
Desktop.ini
ehthumbs.db
Thumbs.db
_~
TAGS
tags
._.sw[a-z]
.netrwhist
*.un~

Essa é uma forma de separar?
# Project

**Comment by fdaciuk** [comment]
Opa @theandersonn, qual o número do vídeo que fica sem áudio? Olhei aqui o #9 e o #10. Os dois estão normais em 1:50. Será que ele chegou a carregar todo pra você? Pode conferir pra mim certinho? :)

Obrigado pelo feedback ;)

Sobre a sua dúvida: quando você usa o `#` antes de uma palavra, significa que é um comentário. Ele é ignorado pelo git.

Essa separação que tem no `.gitignore` do Odin pode ser feita em qualquer projeto. O que está sendo feito ali é:

Onde diz `# Global`, significa que são os arquivos padrão de sistema, que são gerados automaticamente, arquivos de configuração de editores, etc., que não fazem parte do projeto em si.

E em `# Project`, são os arquivos do projeto mesmo que serão ignorados.

Ficou claro? :)

**Comment by theandersonn** [comment]
@fdaciuk pela manhã no trabalho eu estava assistindo utilizando o firefox e não saia por som no vídeo #10. Mas aqui em casa foi de boa, testei no firefox e chrome. 
 Foi mal, está tudo certo com o aúdio :)

Entendi o ponto dos arquivos no .gitignore.

**Comment by fdaciuk** [comment]
Show @theandersonn! Pode ter sido algum problema com a internet xD

Qualquer dúvida grita aqui ;)
