### ISSUE TITLE
[Aula 2] Duvida com cygwin

### ISSUE THREAD

**Issue by guilhermetempesta** [da2k/curso-git-e-github-ninja#10]
@fdaciuk Não consigo executar vários comandos que vc mostra nas aulas, como por exemplo:
npm, ll, vim... estou usando o cygwin no windows 7 e gostaria de saber se tem alguma solução para o problema. Agradeço desde já.

**Comment by fdaciuk** [comment]
Oi @guilhermetempesta! No windows os comandos são um pouco diferentes.
O ideal era ver na documentação do cygwin quais os comandos para listar arquivos, criar arquivos, etc., que você pode usar.

No meu caso, como estou usando o `oh-my-zsh` no terminal, ele já tem alguns _alias_ pré-configurados.

Então o `ll` que eu uso é o mesmo que `ls -la`. No caso do NPM ou VIM, você precisaria ter o Node.js (com NPM) e o VIM instalados na sua máquina pra esses comandos funcionarem =)

**Comment by jairoduarteribeiro** [comment]
Eu uso o próprio Git bash que vem junto com a instalação do Git. E como editor de texto estou usando o Visual Studio Code, que permite que eu integre o Git bash nele ou qualquer outro terminal, além de ter muitos plugins interessantes. O sublime text também é muito bom como editor de texto.

**Comment by guilhermetempesta** [comment]
@fdaciuk e @jairoribeiro167 Muito obrigado pela explicação! Passei a usar o Git bash e agora está tudo OK.

**Comment by fdaciuk** [comment]
Legal @guilhermetempesta! Qualquer dúvida, só avisar =)
