### ISSUE TITLE
[Aula 6] Dúvida no comando: git config --global credential.helper cache

### ISSUE THREAD

**Issue by guilhermetempesta** [da2k/curso-git-e-github-ninja#11]
Bom dia @fdaciuk , estou com problemas referentes as credenciais ao executar o comando push no terminal.

Na primeira vez que utilizei o comando push, a senha foi solicitada. Porém, nas próximas vezes, não precisei digitar. O problema é que quando configurei a propriedade: credential.helper cache ou credential.helper 'cache --timeout=3600', e fui fazer o push, o terminal (no meu caso, estou usando o Git Bash no Windows) mostra a seguinte mensagem:
git: 'credential-cache' is not a git command. See 'git --help'.

Parece que a configuração não está sendo reconhecida, e mesmo fazendo este comando, eu não precisei digitar minha senha nenhuma vez ao fazer o push, exceto na primeira vez.
O que pode estar ocorrendo?

Obrigado!

**Comment by fdaciuk** [comment]
Oi @guilhermetempesta! Por acaso você tentou executar o comando `git credential-cache`? Pois pelo erro, é o que parece estar acontecendo =)

**Comment by fdaciuk** [comment]
Oi @guilhermetempesta! dei uma pesquisada sobre esse erro, e parece acontecer no windows mesmo:
https://stackoverflow.com/questions/11693074/git-credential-cache-is-not-a-git-command

Tente remover o `credential.helper` (com `--unset`), e depois tente executar o comando de cache, mas usando `wincred` ao invés de `cache`, dessa forma:

```
git config --global credential.helper wincred
```

Me diga se isso funciona pra você, pois não tenho windows pra testar :)

**Comment by guilhermetempesta** [comment]
@fdaciuk 
Usei o comando wincred e não deu mais a mensagem de erro. 
Porém, não respeita o valor colocado no timeout=3600, ou seja, nunca pede a senha novamente desde a primeira vez que a digitei no terminal.

**Comment by fdaciuk** [comment]
@guilhermetempesta tente usar o `unset` pra remover a configuração do `credential.helper` e depois setar novamente com o timeout, mas usando `wincred` no lugar do `cache` :)

**Comment by guilhermetempesta** [comment]
Ok @fdaciuk, vou testar desta forma. Obrigado!

**Comment by fdaciuk** [comment]
Legal! Qualquer coisa avisa ae =)
