### ISSUE TITLE
[Aula 8] Erro ao fazer o push 

### ISSUE THREAD

**Issue by guilhermetempesta** [da2k/curso-git-e-github-ninja#12]
@fdaciuk , você poderia me ajudar com um erro que ocorre ao executar o comando "git push origin js"? 

Exibe a seguinte mensagem:

$ git push origin js
failed to load advapi32.dll
Counting objects: 11, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (10/10), done.
Writing objects: 100% (11/11), 1.75 KiB | 895.00 KiB/s, done.
Total 11 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), done.
To https://github.com/nome/ecommerce.git
 ! [remote rejected] js -> js (permission denied)
error: failed to push some refs to 'https://github.com/nome/ecommerce.git'

**Comment by fdaciuk** [comment]
Oi @guilhermetempesta! Esse erro é por causa da permissão no seu repositório =)

Veja a penúltima linha:

```
! [remote rejected] js -> js (permission denied)
```

Você chegou a subir sua chave SSH no GitHub? Ou, se estiver usando https, veja se colocou a senha certa na hora de tentar fazer o push =)

**Comment by guilhermetempesta** [comment]
@fdaciuk ainda não consegui resolver o problema da minha senha no terminal, eu digitei a primeira vez, teria alguma maneira de resetá-la?
Não cheguei a usar SSH ainda, estou usando https mesmo...

**Comment by fdaciuk** [comment]
Oi @guilhermetempesta! Você usou o `credential.helper` para setar a senha e não precisar ficar digitando? Se sim, só dar `unset` na mesma configuração (mostrei na aula como setar e dar unset) que você remove as credenciais anteriores =)

Depois você só precisar setar novamente, se não quiser ficar digitando a senha sempre =)

**Comment by fdaciuk** [comment]
Oi @guilhermetempesta! Vou fechar a issue, mas se vc ainda tiver qualquer problema, só avisar que eu te ajudo, ok? =)
