### ISSUE TITLE
[Aula 2] Vídeo #07

### ISSUE THREAD

**Issue by ghost** [da2k/curso-git-e-github-ninja#13]
@fdaciuk Na aula você mostrou que o git add . não levava os arquivos deletados para a staging area, porém fiz os testes e aqui ao executar o git add . ele leva todos arquivos para staging area, inclusive os deletados.

Saberia me dizer se isso é algo que mudou nas versões mais novas do git?

**Comment by fdaciuk** [comment]
Oi @joaonery! Na verdade, quando você tem arquivos alterados E arquivos deletados para serem adicionados na staging area, então o git faz a adição de todos esses arquivos. Agora, se você apenas deletar, ele não deve adicionar com `git add .` =)

Dá uma olhada se não é esse o seu problema =)

E desculpe a demora na resposta, por algum motivo não recebi notificação da sua dúvida :\

**Comment by ghost** [comment]
Entendi, Obrigado.

**Comment by fdaciuk** [comment]
Legal! Qualquer dúvida, só avisar =)
