### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by alexandre1202** [da2k/curso-git-e-github-ninja#14]
Oi Fernando @fdaciuk

Aqui vc ensinou sobre como deletar uma branch mas se não estou ficando completamente louco, anteriormente vc ensinou com outro comando que seria o 
git branch -D <nomedabranch>

Por favor existe alguma diferença?

Obrigado

**Comment by fdaciuk** [comment]
Oi @Alexandre1202! A qual comando você se refere, além do `git branch -D`?

**Comment by alexandre1202** [comment]
Na aula 30 vc fala do git push origin <branch> —delete

**Comment by fdaciuk** [comment]
Ah sim! No caso, como eu mostrei no vídeo, o `git branch -D` vai deletar a branch "local" (apenas na sua máquina).

Ao usar o `git push origin --delete`, a branch do repositório será deletada (no caso, a branch "dev" que está no GitHub) =)
