### ISSUE TITLE
[A45] upstream

### ISSUE THREAD

**Issue by alexandre1202** [da2k/curso-git-e-github-ninja#15]
Oi @fadciuk 

Por favor, vc criou a origin upstream para exemplificar a utilização de um nome diferente ou também é comum trabalharmos normalmente em time com a origin master mesmo?

Também não entendi quando devemos fazer o fork. Eu sempre comecei com o clone e o time trabalha remoto dessa forma mais trivial sem fork

**Comment by fdaciuk** [comment]
Oi @Alexandre1202! Desculpe a demora na resposta: como você marcou meu usuário errado, eu acabei não recebendo a notificação, e só vi sua dúvida agora :\

Vou tentar melhorar isso, adicionando automaticamente meu nome de usuário quando uma nova issue for aberta =)

Agora, sobre a sua dúvida: sobre o `origin` e `upstream`: o `origin` é padrão do git, mas você consegue dar qualquer nome para representar algum repositório remoto. O mais comum é sempre `origin` e `upstream`, mas nada impede de você usar outros nomes para isso =)

Sobre o fork, normalmente você faz em algumas situações:
- quando o projeto é de terceiros, e você não tem acesso ao respositório para fazer `push`, então você faz um fork, faz as alterações necessárias, e faz o `push` no seu repositório. À partir desse ponto, você pode solicitar para dono do repositório original uma requisição para ele fazer `pull` (Pull Request).
- outra situação é quando você trabalha em times grandes: normalmente você não vai ter permissão para fazer `push` diretamente no repositório principal, pois o time todo poderia perder o controle da situação. Então você faz um fork, e escreve sempre no seu fork. Para que o merge seja feito no repositório principal, normalmente usamos alguma ferramenta de CI (como Jenkins ou Travis), fazendo com que o processo de merge seja automatizado =)

Mas para times pequenos, dificilmente você teria problemas, e se tiver, fica bem mais fácil de resolver, ainda que todos estejam comitando e fazendo push no mesmo repositório =)

Ficou claro? =)

**Comment by alexandre1202** [comment]
Sim @fdaciuk  ficou claro sim.
Muito obrigado pela atenção mais uma vez.
Até breve

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar! =)
