### ISSUE TITLE
[aula-2/5] - git commit

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-git-e-github-ninja#16]
Olá, professor. 

Tentei configurar o vscode para editar as mensagens de commit mais detalhadas, mas não consegui. 
E agora, o vim também não está sendo aberto ao executar o `git commit`. 

Problemas: 

- Se edito a mensagem no vscode, salvo e fecho o arquivo. "Aborting commit due to empty commit message" é mostrada
- Executo `git config core.editor` e o retornado é "code --wait", ou seja, o vscode está setado como o editor... 

- Se executo `git config --global core.editor vim`, para mudar para o vim, e, em seguida `git config --global -e`, é retornado "hint: Waiting for your editor to close the file... fatal: cannot run vim: No such file or directory error: unable to start editor 'vim'"

Se executo `git commit`, a mensagem retornada é: 
"hint: Waiting for your editor to close the file... fatal: cannot run vim: No such file or directory 
error: unable to start editor 'vim' 
**Please supply the message using either -m or -F option."**"

Será que não vai ser possível o `git commit` funcionar aqui? E claro, meu SO é o rwindows... 

@fdaciuk

**Comment by Roger-Melo** [comment]
Deu certo, professor. Valeu kkk

**Comment by fdaciuk** [comment]
Opa @Roger-Melo! Desculpe, não tinha visto sua mensagem ainda! Que bom que resolveu =)
