### ISSUE TITLE
Código privado no GitHub

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-git-e-github-ninja#17]
Terminei o curso, professorrr! :beers:

Em uma das aulas, você comentou sobre uma forma de ter códigos privados no GitHub, free.
Seriam apenas os secret Gists mesmo?

@fdaciuk

**Comment by fdaciuk** [comment]
Opa, show de bola @Roger-Melo! Parabéns \o/
Sobre os repositórios, eu sei que o GitHub tem um programa para estudantes / professores, dá uma olhada se você consegue algo:
https://education.github.com/students

Mas repositórios privados free você consegue usando o [Bitbucket](https://bitbucket.org/) ou [GitLab](https://about.gitlab.com/) =)

**Comment by Roger-Melo** [comment]
Bacana, professor. Obrigado!
