### ISSUE TITLE
Trocar o tipo de  LICENSE de mit para agpl é possível ?

### ISSUE THREAD

**Issue by Matiusco** [da2k/curso-git-e-github-ninja#19]
Criei um repositório e durante a criação escolhi a licença mit. Depois percebi que o ideal seria agpl. Não consegui encontrar onde mudar a licença. Apaguei o repositório porque era apenas pra fixar o aprendizado e criei um nome com a licença agpl. 
Seria legal saber se tem como alterar porque pode ser uma dúvida de outras pessoas.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Matiusco! Você até pode fazer a alteração da licença, mas precisa se atentar à versão do seu software.

Normalmente projetos open source seguem o padrão _semver_, ou [_Semantic Versioning_](https://semver.org/), para ficar fácil saber quando foi corrigido um bug de um software (_patch_),  quando uma nova feature foi disponibilizada (_minor_), ou quando foi gerada uma versão que não é compatível com versões anteriores (_major_).

Para mudanças de uma licença mais restritiva, é importante usar a atualização _major_, para dizer que, à partir dessa nova versão, a licença em uso é essa mais restrita que você colocou.

Para mudar para uma licença menos restritiva, uma versão _minor_ é o suficiente.

O importante é isso estar documentado e bem separado por versões, para que o usuário saiba qual versão do seu software ele pode usar com uma licença específica.

Mas você não deve nunca mudar uma licença sem mudar a versão também.

Ficou claro?

**Comment by Matiusco** [comment]
Obrigado @fdaciuk , ficou super claro sim. 
Estou na lição de markdown agora.

**Comment by fdaciuk** [comment]
Perfeito! Qualquer dúvida, só avisar =)
