### ISSUE TITLE
[Aula 02] Vídeo #11 - Dificuldade em confirmar alteração no vim 

### ISSUE THREAD

**Issue by theandersonn** [da2k/curso-git-e-github-ninja#2]
@fdaciuk estou com uma pequena dificuldade em confirmar alterações no vim.

Aqui estou utilizando o Windows tentei uma operação como por exemplo a reversão de um commit, ao abrir o vim após a mensagem de confirmação digitei :wq  mas não consigo confirmar.

Outra situação é quando tentei alterar o editor para o Atom, quando abre o vim, não consigo confirmar a alteração, simplesmente não sai da tela do vim.

**Comment by theandersonn** [comment]
@fdaciuk Matei a xarada!

No VIM para inserir a mensagem temos que:

Pressionar i para entrar no modo de inserção

Após digitar a mensagem, pressionar esc e depois :wq e enter para confirmar.

Sei nada de VIM :(

**Comment by fdaciuk** [comment]
Opa! É isso mesmo! O vim tem esses dois modos xD
É interessante aprender algumas coisas dele, ou talvez usar um outro editor no lugar :)

**Comment by theandersonn** [comment]
@fdaciuk Configurei o Atom e fiz alguns testes, mas deu um pequeno bug nas confirmações. Optei por deixar o vim para essas confirmações do git.

Issue resolvida.

**Comment by fdaciuk** [comment]
Pois é.. nesses casos acho que o vim funciona melhor que um editor visual xD
