### ISSUE TITLE
Todas extensões .sh ignoradas no .gitignore mas tenho um arquivo pra manter

### ISSUE THREAD

**Issue by Matiusco** [da2k/curso-git-e-github-ninja#20]
no gitgnore quero ignorar todos arquivos com a extensão .sh (bash shell) , mas tem um determinado arquivo que preciso que ele vá para o repositório remoto. 
Qual a forma segura de fazer isso ? 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Matiusco! Você pode fazer isso com duas linhas: na primeira, você ignora todos os arquivos que terminal com `.sh`, usando `*.sh`. Na segunda linha, você diz que não quer ignorar o `a.sh`, por exemplo, então é só usar o operador de negação `!`. Seu `.gitignore` ficaria assim:

```
*.sh
!a.sh
```

Lembrando que, se esses arquivos já foram adicionados com `git add`, é preciso remover antes eles da árvore do `git` pra isso funcionar =)

**Comment by Matiusco** [comment]
+1

**Comment by fdaciuk** [comment]
Qualquer coisa avisa ae =)
