### ISSUE TITLE
Terminal Gnome

### ISSUE THREAD

**Issue by marceloolima** [da2k/curso-git-e-github-ninja#21]
Boa tarde, como faço para customizar o terminal do linux para deixar como o seu, utilizo o debian 9 e é um saco ficar dando o comando git branch para confirmar se estou na branch certa.

Agradeço pela atenção.
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @marceloolima! Eu uso o shell ZSH com a extensão [`oh-my-zsh`](https://github.com/robbyrussell/oh-my-zsh).

Essa extensão tem alguns temas e alias já configurados bem legais, dá uma olhada =)

**Comment by marceloolima** [comment]
Excelente este shell @fdaciuk , muito obrigado mesmo.

Agora mãos a obra : )

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar =)
