### ISSUE TITLE
Utilização do Gists

### ISSUE THREAD

**Issue by luchiago** [da2k/curso-git-e-github-ninja#22]
Ainda não entendi muito bem a função dos Gists e a diferença entre eles e um repositorio comum

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @luchiago! A ideia do gist é criar trechos de códigos rapidamente. 

Ao invés de criar um repositório com um projeto, você pode querer, por exemplo:
- colocar apenas um trecho de código e passar como dica para um amigo, 
- ou algum trecho de código que você queira lembrar no futuro, 
- ou ainda, quando estiver com alguma dúvida, e fizer alguma pergunta em um fórum, o gist é uma forma rápida de você mostrar como está o seu código para receber ajuda mais facilmente =)

**Comment by luchiago** [comment]
Ah sim. Agora ficou mais claro. Valeu @fdaciuk

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar :D
