### ISSUE TITLE
[Aula 7] Integração do ???? e vim com git

### ISSUE THREAD

**Issue by alexandredbm** [da2k/curso-git-e-github-ninja#23]
Boa tarde.

Como é feito a integração do editor "Sublime Text" com o git ? Algum plugin ?

Existe como fazer a mesma coisa com o VIM ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @alexandredbm! Você quer saber como "marcar" as linhas que foram alteradas, com base no histórico do git?

Se for isso, tem alguns plugins para o Sublime Text e Vim que fazem isso sim :D 

Pesquisando por "Sublime Text git" ou "Vim git" você vai encontrar várias opções :)

**Comment by fdaciuk** [comment]
Oi @alexandredbm! Conseguiu resolver? Vou fechar a issue, mas qualquer dúvida, só avisar que a gente reabre e eu te ajudo, beleza? :)
