### ISSUE TITLE
Cygwin não faz push para o Github

### ISSUE THREAD

**Issue by DiegoBezerra89** [da2k/curso-git-e-github-ninja#24]
Olá professor!
Estou tendo um problema ao tentar dar o comando:
git push origin master (origin com url github)

o cygwin simplesmente não faz nada, pula pra linha de baixo e fim.

Valeeeeu!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @DiegoBezerra89! Nenhuma mensagem é exibida no terminal?

Cola aqui pra mim, por favor, o resultado do comando:

```
git remote -v
```

**Comment by DiegoBezerra89** [comment]
Boa tarde professor!
Testei aqui no pc do trampo e foi. 


origin  https://github.com/DiegoBezerra89/githubninja.git (fetch)                
origin  https://github.com/DiegoBezerra89/githubninja.git (push)

No meu pc estava com problema, darei uma olhada hoje e aviso se acontecer novamente.
Obrigado pela ajuda!

**Comment by fdaciuk** [comment]
Legal @DiegoBezerra89! Tem que dar uma olhada se no seu PC estão corretos os valores do `remote` =)
Mas que bom que deu certo! Qualquer coisa, só avisar =)

**Comment by DiegoBezerra89** [comment]
Boa tarde professor, 

No meu pc realmente não funciona, não sei o que há. Porém, instalei o Github Desktop e tá funcionando normal pelo push origin. Caso alguém tiver esse mesmo problema, recomendo utilizar o Github Desktop.
Obrigado pela assistência!
Abraços!

**Comment by fdaciuk** [comment]
Oi @DiegoBezerra89! Provavelmente é algum problema de conexão que o GitHub Desktop já configura automaticamente pra você =)

Pode usar essa ferramenta sem problemas, mas tente ao menos compreender o que está sendo passado na linha de comando. É importante saber rodar os comandos pois pode acontecer situações onde você precise usar o Git em um servidor, e nesse tipo de ambiente você normalmente não tem acesso a um ambiente gráfico =)
