### ISSUE TITLE
GIT DIFF

### ISSUE THREAD

**Issue by douglas-88** [da2k/curso-git-e-github-ninja#25]
Bom dia Fernando, tudo bem ?
Queria saber a diferença ao se usar GIT DIFF --STAGE e o GIT DIFF (sem o --STAGE) .

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @DouglasFFBraga! =)

Quando você adiciona arquivos com `git add`, e depois altera esses arquivos, você pode verificar o que mudou desde a última vez que você fez a adição deles, usando `git diff`, pois essa última alteração você estará fazendo no _working directory_.

Mas quando você adicionou com `git add`, e já fez um commit, e então começa a alterar os arquivos novamente, e faz mais um `git add` (antes de fazer um novo commit), você já não consegue mais ver as alterações usando `git diff`, pois os arquivos já estarão na _stagging area_.

Se você rodar um `git log` com alguns arquivos adicionados, você vai ver a mensagem: 

```
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   nome-do-arquivo
```

Veja que a mensagem diz que existem alterações a serem comitadas. E essas alterações agora estão na _stagging area_. Para remover da _stagging area_, ele diz que podemos usar o comando `git reset HEAD <file>`.

E para ver alterações de arquivos que estão nessa _stagging area_, nós usamos o `git diff` com o parâmetro `--staged`.

Então basicamente essa é a diferença: sem o `--staged` você vê as diferenças dos arquivos no _working directory_. Já usando o `--staged`, você vê as alterações nos aquivos que já estiverem na _stagging area_ =)

**Comment by fdaciuk** [comment]
Oi @DouglasFFBraga! Conseguiu entender essa parte? Vou fechar a issue, mas qualquer dúvida, só avisar que a gente reabre e eu te ajudo, beleza? :)
