### ISSUE TITLE
[Aula 04] Logs personalizados

### ISSUE THREAD

**Issue by ThalesAlonso** [da2k/curso-git-e-github-ninja#26]
Boa tarde professor, teria como disponibilizar os slides ou um txt dos comandos dos logs personalizados ? 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ThalesAlonso! Claro! Me manda, por favor, via DM pela Udemy um e-mail que você tenha acesso ao Google Drive, que eu te passo o acesso aos slides :)

**Comment by ThalesAlonso** [comment]
Valeu Professor, já mandei a DM

**Comment by ThalesAlonso** [comment]
Valeu Professor, já recebi por  e-mail.

**Comment by fdaciuk** [comment]
Show! Qualquer coisa só avisar :D

**Comment by DouglasFFBraga** [comment]
Tem como me passar os slides com os comandos GIT para o meu e-mail também: dcdouglas64@gmail.com

**Comment by fdaciuk** [comment]
Oi @DouglasFFBraga! Enviei! =)
Deletei seu comentário apenas para não ficar seu e-mail público aqui, pra evitar bots e spams :)
Quando for enviar informações sensíveis assim, pode mandar via DM pela Udemy, ok? :)

**Comment by douglas-88** [comment]
> Tem como me passar os slides com os comandos GIT para o meu e-mail também?

Já recebi os slides em meu e-mail.
Seu suporte aos cursos é bem rápido e efiente. 
Tá de parabéns. kk
