### ISSUE TITLE
Indentando Headings

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-git-e-github-ninja#27]
Oi professor. Eu estava experimentando uma forma de deixar minhas anotações mais organizadas, indentando os headings e parágrafos. Me deparei com um pequeno problema: se um texto é indentado com 4 espaços, [o GitHub assume que ele é um bloco de código](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown). Você conhece alguma técnica para evitar isso? 

![image](https://user-images.githubusercontent.com/29297788/53671373-d2096680-3c5c-11e9-85da-bd9a773edf3c.png)

![image](https://user-images.githubusercontent.com/29297788/53671604-ef8b0000-3c5d-11e9-93be-4ccab91e927e.png)

@fdaciuk

**Comment by fdaciuk** [comment]
O correto, ao escrever markdown, é não indentar. Espaços contam para arquivos HTML, assim como para markdown :)

**Comment by Roger-Melo** [comment]
feshow, professor. Estou pesquisando outras formas além da indentação. Valeus =)

**Comment by fdaciuk** [comment]
Perfeito @Roger-Melo!

Acho que a única forma visual de separar sem ter problemas é usando linhas vazias. Isso eu sei que não conta, nem no HTML, nem no MD :)
