### ISSUE TITLE
[Aula 8] Arquivo .gitignore

### ISSUE THREAD

**Issue by eduardotrandafilov** [da2k/curso-git-e-github-ninja#28]
Estou utilizando a versão do git 2.21 , porém , não estou conseguindo entender porque mesmo quando baixo o node_modules pelo npm e posteriormente digito no terminal do ubuntu 16.04 "git status" não está havendo a exibição do diretório mesmo não tendo incluído no .gitignore. 

Poderia me dar um help nessa dúvida?!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @eduardotrandafilov! Veja se você não tem um `.gitignore` no seu diretório _Home_. Normalmente isso é usado para ignorar, por padrão, de forma global, alguns diretórios comuns em muitos projetos :)

**Comment by eduardotrandafilov** [comment]
Boa! Encontrei o .gitignore que estava no meu diretório home , mas além disso havia também uma configuração global que tinha setado o parâmetro core.excludesfile para considerar o conteúdo que estava no .gitignore  desse diretório.

Valeu! @fdaciuk

**Comment by fdaciuk** [comment]
Show de bola! Qualquer coisa, só avisar :)
