### ISSUE TITLE
Duvida ao fazer o push do meu arquivo

### ISSUE THREAD

**Issue by luizrolim123** [da2k/curso-git-e-github-ninja#29]
Eu estou tentando fazer push no arquivo toda vez que eu digito git push -u origin master
o terminal me manda a mensagem
error: failed to push some refs to 'https://github.com/luizrolim123/vimrc.git'
também tentei o comando 
 git push origin -f
mas ele só me retorna a mensagem
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master
e quando digito ele me retorna
error: src refspec origin does not match any.
error: src refspec master does not match any.

alguém manja o que eu posso fazer pra consertar?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @luizrolim123! Passa pra mim o que retorna do comando abaixo:

```
git remote -v
```

**Comment by luizrolim123** [comment]
origin	https://github.com/luizrolim123/vimrc.git (fetch)
origin	https://github.com/luizrolim123/vimrc.git (push)
hum.. se pá eu deveria sair dessas pastas?

**Comment by fdaciuk** [comment]
Ok, seu repositório está configurado corretamente com HTTPS.. ao fazer o `git push origin master`, ele deveria pedir seu usuário e senha do GitHub. Ele pede isso?

Senão, poderia postar a mensagem de erro inteira aqui pra eu dar uma olhada?

**Comment by luizrolim123** [comment]
então mano mas eu quero upar os arquivos dessa mesma pasta pra uma pasta diferente da vimrc, será que por isso que não tá dando conflito ?

**Comment by luizrolim123** [comment]
então, quando eu logo na pasta ele me dá o seguinte aviso.
error: update_ref failed for ref 'refs/remotes/origin/master': cannot lock ref 'refs/remotes/origin/master': Unable to create '/home/luiz/.git/refs/remotes/origin/master.lock': Permissão negada
Everything up-to-date

**Comment by fdaciuk** [comment]
> então mano mas eu quero upar os arquivos dessa mesma pasta pra uma pasta diferente da vimrc, será que por isso que não tá dando conflito ?

Não entendi o que você quis dizer. `.vimrc` é um arquivo, não um diretório. O que você está tentando fazer?

---

> então, quando eu logo na pasta ele me dá o seguinte aviso.
error: update_ref failed for ref 'refs/remotes/origin/master': cannot lock ref 'refs/remotes/origin/master': Unable to create '/home/luiz/.git/refs/remotes/origin/master.lock': Permissão negada
Everything up-to-date

Essa linha aqui: 
```
Unable to create '/home/luiz/.git/refs/remotes/origin/master.lock': Permissão negada
```

Está dizendo que o diretório atual está sem permissão de escrita, então o `git` não está conseguindo criar alguns arquivos necessários para versionar corretamente.

Pelo que parece, você criou um repositório dentro da seu diretório Home, é isso mesmo?

Se você quer fazer backup de alguns arquivos, o ideal seria criar um diretório separado, e iniciar o git nesse diretório, colocando ali os arquivos que você quer fazer esse backup; não iniciar o git no seu diretório Home :)

É isso mesmo que você está tentando fazer?

**Comment by luizrolim123** [comment]
mano, eu não seu asuhasuhsauas eu só pus os comandos de fazer push na pasta, eu queria mandar vairos arquivos pra diferentes diretórios na mesma pasta home, tu teria alguma dica do que eu poderia fazer?

**Comment by fdaciuk** [comment]
Certo, vamos por partes então :)
A primeira coisa a fazer é: nunca tente versionar um diretório de sistema. Sempre crie um diretório seu, e nesse diretório você inicia o git, adiciona os arquivos que quer versionar ali, e faz o versionamento :)

Então o que você tem que fazer primeiro é remover o diretório `.git` do seu `/home/luiz`;

Depois, crie um novo diretório em algum lugar, e inicie o git ali dentro (clonando o seu repositório, ou iniciando do zero, com `git init` e depois setando o `remote`, para apontar para o seu repositório;

Então é só colocar nesse diretório os arquivos que você quer versionar, comitar e fazer o push :)

Basicamente isso :)

**Comment by luizrolim123** [comment]
ah! valeu ! mas não consigo fazer o up pra dois repositorios diferentes estando na mesma pasta?

**Comment by fdaciuk** [comment]
Consegue sim.. só adicionar dois `remote` com nomes diferentes =)

**Comment by luizrolim123** [comment]
sorry, eu sou muito noob, então eu poderia usar o remote com nome diferente nessa pasta? e ai não daria conflito certo?

**Comment by fdaciuk** [comment]
Nesse diretório que você passou nos comentários acima, por ser um diretório do sistema, não é recomendado fazer isso; mas consegue sim, e não dá conflito não, pelo contrário :)

Nesse curso, inclusive, eu mostro como usar dois repositórios, quando você precisa contribuir com código seu para um outro repositório que não é seu.. aí você adiciona um `origin` e um `upstream` (não sei se você já chegou nessa aula; se não chegou, vale a pena continuar o curso pra ver como isso funciona) =)

Mas nada impede de você ter dois repositórios diferentes, e adicionar os dois como remote para o mesmo projeto :)

**Comment by fdaciuk** [comment]
Oi @luizrolim123! Conseguiu entender essa parte? Vou fechar a issue, mas qualquer dúvida, só avisar que a gente reabre e eu te ajudo, beleza? :)
