### ISSUE TITLE
[Aula 03] Vídeo #15 - Remover mais de um arquivo com status "deleted" da work directory

### ISSUE THREAD

**Issue by theandersonn** [da2k/curso-git-e-github-ninja#3]
Oi @fdaciuk :)

Se eu deleto um arquivo ele fica na minha work directory como deleted e para remover o mesmo é:
git rm nome-aquivo.extensao

Qual é o comando para remover mais de um arquivo com o status deleted da work directory?

Na aula 3 foi utilizado o git rm -rf . (esse deleta de fato todos os arquivos do projeto, confirma?)

**Comment by fdaciuk** [comment]
Opa @theandersonn! Se você utilizar o `git rm -rf .`, ele irá remover todos os seus arquivos, tanto fisicamente, quanto da árvore do git :)

Para que você possa "adicionar para commitar" os arquivos removidos, para que eles sejam removidos somente da árvore do git, você pode usar o comando `git add --all`.

Isso faz o mesmo que o `git add .`, só que inclui também os arquivos que foram deletados :)

**Comment by theandersonn** [comment]
Obrigado pelo esclarecimento, testei aqui e funcionou perfeitamente :)
