### ISSUE TITLE
Repositórios

### ISSUE THREAD

**Issue by ouluka** [da2k/curso-git-e-github-ninja#30]
Boa noite,

Estou tentando implementar um repositório git local, porém do lado do servidor não consigo visualizar os arquivos, isso é comum? Gostaria de executar estes arquivos ao dar push para o server...

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @OuLuka! Para que o servidor consiga acessar os arquivos, ele precisa ter acesso ao repositório.
Se você criou o repositório local, o servidor precisará de alguma forma de acesso ao seu computador.

Normalmente quando você precisa acessar seu repositório em diferentes locais, o ideal é sempre criar o repositório em algum servidor onde você tenha acesso à partir de todos esses locais.

Essa é a vantagem do GitHub, Bitbucket e GitLab, por exemplo: são serviços onde você consegue criar o seu repositório de forma que ele poderá ser acessado de qualquer lugar, desde que você tenha seu ambiente configurado corretamente :)

**Comment by ouluka** [comment]
Na estrutura da empresa hoje, temos 1 servidor de testes para 3 devs e 1 servidor de produção, usamos simplesmente o SFTP sem controle de versão. Eu gostaria de implantar o Git para ter esse controle, então você sugere trocar esse servidor de testes pelo GitHub ou Bitbucket e automatizar o deploy somente na máquina de produção com GIT_WORK_TREE?
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @OuLuka! Com certeza adicionar o git no workflow de vocês vai ajudar muito! Mas ele vai ajudar apenas a deixar tudo mundo sempre com as mesmas versões do código.

Mantenha o servidor de testes para homologação, e quando tiver certeza que tudo estiver 100%, aí você pode fazer o deploy em produção.

Existem, inclusive, várias ferramentas que ajudam nesse processo de deploy (só pesquisar por Continuous Delivery que você vai achar várias), e que podem facilitar bastante o processo de deploy à partir de um repositório git :)
