### ISSUE TITLE
Advertências de Vulnerabilidade no GitHub

### ISSUE THREAD

**Issue by douglas-88** [da2k/curso-git-e-github-ninja#31]
Bom dia Professor Fernando, tudo bem ?
Primeiramente gostaria de lhe parabenizar pelo curso na Udemy, aos poucos estou perdendo o "medo" do GIT.
Mas há algo que sempre acontece comigo quando dou o PUSH no meu repositório remoto, o GITHUB fica me avisando de umas advertências de vulnerabilidade e não deixa eu efetuar o PUSH enquanto não resolver.
Porque isso acontece ?
Segue um print que ilustra:
![Captura de tela de 2019-07-24 09-43-04](https://user-images.githubusercontent.com/10869960/61794618-ee6a9300-adf7-11e9-8358-361ea495c31b.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @DouglasFFBraga! Legal, que bom que está conseguindo aprender direitinho :D 

Essa mensagem é uma nova feature do GitHub: é uma extensão que avisa sempre que você usar no seu projeto alguma dependência que tenha problemas de segurança conhecidos.

Essa extensão "varre" o seu arquivo `package.json` (no caso de projetos em Node), e verifica a dependência e a versão usadas, e te avisa se alguma tem problemas de segurança :)

Se você estiver usando essas dependências apenas no ambiente de desenvolvimento, não tem muito o que se preocupar :)

**Comment by fdaciuk** [comment]
Oi @DouglasFFBraga! Conseguiu entender essa parte? Vou fechar a issue, mas qualquer dúvida, só avisar que a gente reabre e eu te ajudo, beleza? :)
