### ISSUE TITLE
git rm e git rm --cached : Dúvida

### ISSUE THREAD

**Issue by douglas-88** [da2k/curso-git-e-github-ninja#32]
Boa tarde Professor.
Estou com uma dúvida com relação ao comando **git rm** .
Sabemos que o comando **git add** adiciona um arquivo a staged area, correto ?
Já o git rm, remove o arquivo de qual lugar , da Working directory, ou da staged area ?
O comando git rm apaga fisicamente o arquivo ou não ?
E qual a diferença entre o git rm para o git rm --cached , cada um remove de um lugar diferente ?

Desde já agradeço a atenção.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @DouglasFFBraga! 

O comando `git rm` serve para remover arquivos que já foram adicionados ao _git directory_ (arquivos que já foram comitados).

Se você usar apenas o comando `git rm`, **sem remover o arquivo antes**, esse arquivo será adicionado à _staging area_ com o status `deleted`, e **também** será removido fisicamente (do _working directory_).

Ao fazer o commit, o arquivo físico será deletado, e será adicionado no histórico do git essa informação.

Usando o mesmo comando, mas com o parâmetro `--cached`, a informação vai para a _staging area_, apenas para dizer que esse arquivo deve ser removido do _git directory_, mas o arquivo físico (_working directory_) vai continuar lá após o commit :)

**Comment by douglas-88** [comment]
Então o comando **`git rm`** só remove coisas que já foram comitadas ?
Eu achava que esse comando era pra remover arquivos da staged area e voltá-lo para a working directory.

**Comment by fdaciuk** [comment]
Sim, o `git rm` só remove o que já foi comitado!
Pense no seguinte: o _working directory_ é a sua estrutura física de arquivos. É a única parte física dessa estrutura, na verdade :)

A _staging area_ é uma área virtual. Arquivos que estão na _staging area_ estão aguardando para serem adicionados, modificados ou removidos do _git directory_, que também é físico, mas contém apenas o histórico das modificações de cada arquivo que ali está adicionado :)

O que você pode fazer é usar o `git rm --cached` para "voltar" um arquivo que esteja na _staging area_, desde que esse arquivo tenha sido adicionado ou modificado :)

**Comment by douglas-88** [comment]
Quando você diz: "_O que você pode fazer é usar o git rm --cached para "voltar" um arquivo que esteja na staging area, desde que esse arquivo tenha sido adicionado ou modificado :)_" .
Você quis dizer "voltar" da **staging area** para a **working directory**, é isso ?

**Comment by fdaciuk** [comment]
Isso mesmo! O arquivo pode voltar a ser _untracked_ se você fizer isso :)

**Comment by douglas-88** [comment]
> Sim, o `git rm` só remove o que já foi comitado!
> Pense no seguinte: o _working directory_ é a sua estrutura física de arquivos. É a única parte física dessa estrutura, na verdade :)
> 
> A _staging area_ é uma área virtual. Arquivos que estão na _staging area_ estão aguardando para serem adicionados, modificados ou removidos do _git directory_, que também é físico, mas contém apenas o histórico das modificações de cada arquivo que ali está adicionado :)
> 
> O que você pode fazer é usar o `git rm --cached` para "voltar" um arquivo que esteja na _staging area_, desde que esse arquivo tenha sido adicionado ou modificado :)

Então o comando `git rm --cached` se eu rodar ele pela primeira vez , em algo que já foi comitado primeiro ele vai fazer com que seja removido do .git repository para a staging area, e se eu rodar ele de novo nesse mesmo arquivo, ele vai mover ele da staging area para a working directory ?

**Comment by fdaciuk** [comment]
Não! Vamos lá:

Iniciamos um novo projeto, vazio. Rodamos `git init` pra iniciar esse projeto, sem arquivos ainda. O diretório `.git` será criado.

Vamos criar um arquivo `a`. Criamos o arquivo, adicionamos ele com `git add a` e comitamos. Pronto, `a` está no _git directory_, ok? :)

Se rodarmos `git rm --cached a`, o arquivo físico continua ali, mas uma instrução é enviada para a _staging area_: o arquivo existia no _git directory_, e eu quero removê-lo de lá, sem removê-lo fisicamente.

Ao rodar `git status`, você vai ver que o arquivo `a` está com status `deleted` na _staging area_, e ele vai aparecer também em uma lista abaixo, como _Untracked_, significando que, assim que um commit for feito, esse arquivo não estará mais sendo trackeado pelo git.

Se antes de comitar você tentar rodar novamente `git rm --cached a`, nada vai acontecer, vai aparecer uma mensagem de erro, do tipo:

```
fatal: pathspec 'a' did not match any files
```

Porque esse arquivo estava no _git directory_, e agora está na _staging area_, com status `deleted`, aguardando o commit.

Esse foi o caso de uso para um arquivo que estava no _git directory_.

Agora, vamos criar um arquivo novo `b`.

Ao criar esse arquivo e rodar o `git add b`, ao executar `git status`, ele vai aparecer na _staging area_ com o status `new file`.

Se ele é um novo arquivo, ele ainda não chegou a ir para o _git directory_. Nesse caso, você pode usar o `git rm --cached b` para removê-lo da _staging area_, e voltar a ser _Untracked_, se o comando `git rm --cached b` for executado antes do commit :)

Ficou claro? :)

**Comment by douglas-88** [comment]
Ah sim, Untracked é a mesma coisa que o arquivo estar na working directory ?
E quando você escreveu `git rm --checked a`, na verdade queria dizer **`git rm --cached a`**, não é ?

**Comment by fdaciuk** [comment]
Sim, _Untracked_ é quando você tem um repositório git iniciado no seu projeto, mas não adicionou o arquivo do _working directory_ ainda, aí ele fica como _Untracked_, significando que o git ainda não consegue "seguir" ou "trackear" as mudanças que forem feitas nesse arquivo :)

isso, foi mal! È `cached` mesmo haha :D
Editei o comentário :)

**Comment by douglas-88** [comment]
Obrigado Fernando por sua dedicação e rapidez em ir me respondendo, agora ficou mais claro para mim.
Sucesso na sua carreira.

**Comment by fdaciuk** [comment]
Show de bola meu caro! Conte comigo sempre que precisar :)
