### ISSUE TITLE
adicionando repositório ao meu projeto

### ISSUE THREAD

**Issue by FabioMauadie** [da2k/curso-git-e-github-ninja#34]
olá professor gostaria de uma ajuda, não estou conseguindo adicionar o repositório ao meu projeto, pode me ajudar por favor.

quando executo o comando 
$  git remote add origin /c/Users/Fabio Mauadie/Desktop/cursoGit/time/servidor/ecommerce.git

aparece esta mensagem 
```

**usage: git remote add [<options>] <name> <url>

    -f, --fetch           fetch the remote branches
    --tags                import all tags and associated objects when fetching
                          or do not fetch any tag at all (--no-tags)
    -t, --track <branch>  branch(es) to track
    -m, --master <branch>
                          master branch
    --mirror[=(push|fetch)]
                          set up remote as a mirror to push to or fetch from**

```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @FabioMauadie! O problema, muito provavelmente, é porque você tem um espaço no seu nome de usuário. Ao rodar um comando no terminal, espaços servem para separar argumentos passados para esse comando. O git está entendendo que o endereço do seu repositório é `/c/Users/Fabio`, pois tudo o que está vindo após o espaço não é um argumento válido, e está sendo ignorado, por causa do espaço.

Tente colocar esse endereço entre aspas, ou escapar o espaço, que deve funcionar =)

Uma das duas opções abaixo:

```
git remote add origin "/c/Users/Fabio Mauadie/Desktop/cursoGit/time/servidor/ecommerce.git"
```

ou

```
git remote add origin /c/Users/Fabio\ Mauadie/Desktop/cursoGit/time/servidor/ecommerce.git
```

Verifique também se esse caminho está correto. Se estiver, qualquer um dos comandos acima deve resolver :)

**Comment by FabioMauadie** [comment]
Muito obrigado professor ... era isso mesmo... coloquei as opções q sugeriu e funcionou :)

estou gostando muito do curso e apreendendo bastante.... Parabéns


@fdaciuk

**Comment by fdaciuk** [comment]
Show de bola meu caro! Qualquer dúvida, só avisar :D
