### ISSUE TITLE
Sugestões de  ferramentas de gif

### ISSUE THREAD

**Issue by eduardotrandafilov** [da2k/curso-git-e-github-ninja#35]
Gostaria de sugestões de ferramentas free  ou mais utilizadas pelos devs para criação de gifs dos projetos que desenvolvo no github  para criar o readme.md

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @eduardotrandafilov! Normalmente com ferramentas de edição de vídeo, você consegue exportar o vídeo no formato GIF. Então seria só você gravar a sua tela, e usar algum editor qualquer (existem vários, você pode pesquisar pelo seu sistema operacional para encontrar o que é mais fácil para o seu uso), e exportar esse vídeo no formato GIF :)

**Comment by eduardotrandafilov** [comment]
Show, vlw @fdaciuk !

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
