### ISSUE TITLE
Curso de CI/CD

### ISSUE THREAD

**Issue by carvalholeo** [da2k/curso-git-e-github-ninja#36]
Opa Daciuk, blz??

Terminei agora o curso na Udemy e queria uma indicação sua pra curso de CI/CD e TDD, pra melhorar meus conhecimentos. Você já tem algum produzido ou pode me indicar algum?7

Valeu!!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @carvalholeo! Não tenho nenhum curso em específico pra te indicar, mas tem um vídeo do @tuliofaria que pode te dar uma boa base do assunto:
https://www.youtube.com/watch?v=-I6ojXKTdSA

Depois é só consultar a documentação de ferramentas como [CircleCI](https://circleci.com), [Travis](https://travis-ci.org/), etc., que você provavelmente já conseguirá fazer uso dessas ferramentas sem muitos problemas :)

Qualquer coisa, só avisar :)

**Comment by carvalholeo** [comment]
Opa, valeu

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
