### ISSUE TITLE
[Aula 01] Dúvidas sobre git add

### ISSUE THREAD

**Issue by MellonFive** [da2k/curso-git-e-github-ninja#37]
Como faz para adicionar arquivos excluídos, não entendi muito bem!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MellonFive! Em qual vídeo da aula 1 você viu isso? Só pra eu conseguir entender o contexto da sua dúvida :)

**Comment by fdaciuk** [comment]
Oi @MellonFive! Vou fechar a issue, mas fique à vontade para perguntar sempre que tiver dúvidas, ok? :)

**Comment by MellonFive** [comment]
Não tem problema man. Qualquer coisa eu dou um grito iashuhasuhas
