### ISSUE TITLE
[AULA 5] - Fechando issue com commit

### ISSUE THREAD

**Issue by NadiaaOliverr** [da2k/curso-git-e-github-ninja#39]
@fdaciuk, caso não exista issue para ser fechada, o git retornaria erro ?

**Comment by fdaciuk** [comment]
Oi @NadiaaOliverr! Como essa é uma feature que não tem a ver com o git em si, mas é específica do GitHub, que analisa a mensagem de commit para fechar uma issue, o git vai seguir com o fluxo normal de um pós commit qualquer :)
