### ISSUE TITLE
[Sugestão de assunto] Deploy de arquivos

### ISSUE THREAD

**Issue by theandersonn** [da2k/curso-git-e-github-ninja#4]
@fdaciuk Essa é uma dúvida que já até comentei com vc.

Pesquisei por algumas soluções mas ainda não consegui matar essa questão.

Exemplo:
Estou trabalhando com o meu projeto versionado, enviando meus arquivos para o GitHub ou Bitbucket e preciso que ao mesmo tempo esses arquivos sejam enviados para o local onde o site está hospedado, ou seja sem precisar fazer ftp.

Qual solução você sugere, podemos considerar no curso?

**Comment by fdaciuk** [comment]
@theandersonn, vai ser difícil caber esse assunto no curso, pois não é algo que dá pra abordar de forma tão rápida.

Mas, basicamente, uma solução seria a utilização de uma ferramenta de CI (continuous integration) e/ou CD (continuous deployment).

Uma ferramenta que pode te ajudar nesse caso, e que se integra bem com o Github é o CircleCI:
https://circleci.com/

**Comment by fdaciuk** [comment]
@theandersonn uma outra ferramenta que pode ser útil: http://devo.ps/

**Comment by theandersonn** [comment]
@fdaciuk Vou olhar as duas sugestões e pesquisar.
Saiu esse artigo no Tableless, me pareceu uma boa.

http://tableless.com.br/usando-git-para-atualizar-arquivos-no-servidor-de-hospedagem/

**Comment by fdaciuk** [comment]
Também dá @theandersonn! A vantagem de usar uma ferramenta de CI é que ela executa seus testes antes de fazer o deploy, garantindo que você não irá enviar código quebrado para a produção :)

Mas para projetos pequenos, essa solução só com git pode fazer sentido :)
