### ISSUE TITLE
[Seção 1][Aula 5] Dúvida sobre git diff

### ISSUE THREAD

**Issue by brunolimadevelopment** [da2k/curso-git-e-github-ninja#40]
Boa tarde 🐱‍👤 @fdaciuk !  
Eu executo o    git diff    e ele só exibe as mudanças do arquivo que está na raiz do projeto.
como eu faço pra ver as mudanças de um arquivo que está dentro de uma pasta.
por exemplo:

projeto
  - css/style.css
  - index.html

queria visualizar as mudanças do style.css também. 🤔

At.te;

**Comment by fdaciuk** [comment]
Oi @brunolimadevelopment! Usando o comando `git diff` (sem mais parâmetros), será exibido as alterações de todos os arquivos **que já haviam sido adicionados** e sofreram alterações, independente da estrutura dele dentro do projeto.

Se o git não está mostrando alterações para o seu arquivo `css/style.css`, provavelmente ele não tinha sido adicionado ainda à arvore do `git` =)

**Comment by brunolimadevelopment** [comment]
@fdaciuk  Como faço pra inserir o arquivo novo na arvore do git??.
fica assim:

<img width="778" alt="sem commit" src="https://user-images.githubusercontent.com/20023147/66274093-58200800-e851-11e9-8ddb-bafc0c4e41bf.PNG">

eu achava que ao criar um novo arquivo executar `git add arquivo` e `git commit ` e em seguida fazer alguma alteração e posteriormente executar o `git diff` ele já iria reconhecer as alterações de todos os arquivos. 🤦‍♂️

**Comment by fdaciuk** [comment]
É exatamente isso: `git add` e `git commit`. Se não mostrou nada quando você rodou o `git diff`, provavelmente não houve alteração naquele arquivo. Tem certeza que você mudou algo nele?

**Comment by fdaciuk** [comment]
Olhando agora para o seu log, aprece que o `git` entendeu seu arquivo `.css` como um arquivo binário. Provavelmente por isso ele não mostrou as alterações.

O que pode ter acontecido é que, ao salvar o arquivo, foi usado um `charset` que fez o `git` reconhecer o arquivo dessa forma.

Tente abrir o arquivo no seu editor de textos, preferido, e, pelo seu editor, selecione o `charset` **utf-8**. Com esse charset, os textos devem ser reconhecidos corretamente como texto, e as alterações serão exibidas.

OBS.: Cada editor de textos tem uma forma de setar o charset, então é necessário pesquisar como fazer para o seu editor atual, ok? :)

**Comment by fdaciuk** [comment]
Oi @brunolimadevelopment! Vou fechar a issue, mas fique à vontade para perguntar sempre que tiver dúvidas, ok? :)
