### ISSUE TITLE
[AULA 06] - Cache de senha

### ISSUE THREAD

**Issue by NadiaaOliverr** [da2k/curso-git-e-github-ninja#41]
@fdaciuk, ao utilizar o comando:

> git config --global credential.helper cache

a senha fica salva por tempo indeterminado ou apenas uma quantidade X de tempo ?

**Comment by fdaciuk** [comment]
Oi @NadiaaOliverr! Por padrão, o `git` deixa a senha salva em memória por `900` segundos (15 minutos). 

Se você quiser definir o tempo, pode passar o parâmetro `--timeout` junto com o `cache` (veja que, nesse caso, é obrigatório o uso de aspas simples para passar o valor como um único parâmetro para `credential.helper`):

```
git config credential.helper 'cache --timeout=300'
```

No caso do exemplo acima, o `git` vai guardar a senha por 5 minutos =)

**Comment by NadiaaOliverr** [comment]
Muito obrigada por sanar todas as dúvidas, curso excelente !

**Comment by fdaciuk** [comment]
Que bom que está curtindo @NadiaaOliverr! Conte comigo para o que precisar :)
