### ISSUE TITLE
Aula1 do curso git & github-ninja

### ISSUE THREAD

**Issue by Script31** [da2k/curso-git-e-github-ninja#42]
@fdaciuk
qual  principal diferenca entre git log e git diff?

**Comment by fdaciuk** [comment]
Oi @Script31! Os dois comandos servem para propósitos diferentes: o `git log` serve para exibir um registro dos commits que já foram feitos.

Já o `git diff` serve para exibir o que foi alterado em arquivos que já estavam comitados antes. Ele mostra o que está diferente de como o arquivo estava no último commit :)
