### ISSUE TITLE
[aula.18 Clonando Repositorios]

### ISSUE THREAD

**Issue by Edinhomarques** [da2k/curso-git-e-github-ninja#43]
Olá Fernando, Tudo bem? Uma duvida na aula 18 quando vc cria varios diretorios servido fernando etc... cheguei no passo de entrar na pasta ana para realizar git clone
[caminho/ana] 
>git clone [caminho que o pwd forneceu na pastar servidor]

> git clone C:\Users\emarquef\Downloads\git-github-ninja-examples\time\servidor\ecommerce.git
Cloning into 'UsersemarquefDownloadsgit-github-ninja-examplestimeservidorecommerce'...
fatal: 'C:UsersemarquefDownloadsgit-github-ninja-examplestimeservidorecommerce.git' does not appear to be a git repository
fatal: Could not read from remote repository.

>Please make sure you have the correct access rights
and the repository exists.

Como proceder? Se você observar o cloning into mais acima sai todo estranho sem as **\\**
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Edinhomarques! O problema provavelmente é a forma que o windows lida com diretórios. Infelizmente, ele é o único "diferentão". O padrão para gerenciamento de diretórios é o padrão Unix, tanto em SOs, como para redes, na web, etc.

O windows usa a barra invertida, que nesses outros sistemas significa um caracteres para escape de outros caracteres especiais.

Para resolver, tem duas formas: ou você coloca duas barras invertidas no caminho - que é bem mais trabalhoso - ou vai pela forma mais fácil: envolve o caminho sempre com aspas:

```
git clone "C:\Users\..."
```

Dessa forma, você consegue "burlar" essa falha que acontece no windows :)

**Comment by Edinhomarques** [comment]
Entendi, mas oq eu achei estranho foi porque eu ja clonei respositorios antes no windows e nunca tive isso, de toda forma entendi. Muito obrigado
@fdaciuk

**Comment by Edinhomarques** [comment]
eu tava usando o bash do git pra poder usar os comandos linux que nem você, testei agora pelo cmd e funcionou o comando git clone com o diretório do windows que peguei usando dir no cmd.

**Comment by fdaciuk** [comment]
Pois é.. cada terminal pode funcionar de um jeito. Provavelmente o cmd funciona porque ele já é do windows, então ele sabe que os caminhos no windows são usados com a barra invertida, aí ele ignora o escape :)
