### ISSUE TITLE
Seção 6: Aula #06 35. (Chave SSH)

### ISSUE THREAD

**Issue by Ataos** [da2k/curso-git-e-github-ninja#44]
Olá, parabéns pelas aulas eu so foquei com uma dúvida sobre chave SSH, qual é a diferença dela? Eu ainda preciso colocar a senha do meu github utilizando chave SSH em um outro computador pessoal?
Se eu tiver dois computadores, o recomendado é usar chave SSH?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Ataos! Você pode criar uma chave SSH com ou sem senha. O ponto é que a validação com chave SSH é diferente de usar usuário e senha. Funciona da seguinte forma:
ao criar uma chave SSH, será criado no seu computador dois arquivos: um será a chave pública, e outro será a chave privada.

A chave privada você **nunca deve compartilhar**, ela deve ficar sempre só no seu computador. Já a chave pública, você irá passar ela para o serviço que você precisa ter acesso via SSH (no caso, o GitHub).

Quando você faz isso, e tenta conectar via SSH com o GitHub, a chave pública que estará registrada no GitHub é baixada para o seu computador, e localmente é comparada com a sua chave privada, que foi criada junto com ela.

Se as chaves "baterem", então a conexão será efetuada.

Ou seja: se outra pessoa tiver posse da sua chave pública, ela não poderá fazer nada sem a chave privada :)

Em resumo, esse é o funcionamento do SSH. E isso funciona não só para o GitHub, mas para qualquer tipo de conexão entre dois computadores.

---

Agora, para criar a chave e subir no GitHub, você só precisa seguir esses tutoriais, de acordo com o seu sistema operacional:
https://help.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

Cada link é uma passo que você precisa seguir. Ao seguir todos os passos, você estará pronto para usar uma conexão via SSH :)

---

Detalhe importante: se você quiser usar mais de um computador, você tem duas opções:
- ou pode criar uma chave para cada PC;
- ou pode usar a mesma chave nos dois PCs. Dessa forma, você não precisa configurar uma chave pública no GitHub para cada PC. Só copiando as chaves para o novo PC, tudo já vai funcionar como no PC que já estava funcionando :)

**Comment by Ataos** [comment]
Ahh eu entendi! No meu ver ainda não tem muitas diferenças do login e password do git, obrigado por ajudar

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
