### ISSUE TITLE
[Seção 3] Aula 17

### ISSUE THREAD

**Issue by lucasmedrado** [da2k/curso-git-e-github-ninja#45]
@fdaciuk Olá Professor estou precisando de ajuda. Meu S.O é o windows e estou utilizando o Cygwin. Estou criando o repositório remoto no git e utilizando o comando "git init --bare", depois de usar esse comando ele imprime a mensagem que criou um repositório vazio no git, depois volto para o meu projeto local master e rodo o comando "git remote add <nome> <caminho repositório>", utilizo o comado "git remote -v" ele imprime a mesma mensagem que imprime na video aula, porém quando utilizo o comando "git push <nome> <branch>" aparce a seguinte mensagem: "fatal: 'C:/Program Files/Git/home/lucas/my-project.git' does not appear to be a
git repository
fatal: Could not read from remote repository."
Professor já pesquisei um monte e não consigo encontrar a solução. Será que o problema está no Cygwin.
Obs: Meu windows é o 10

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @lucasmedrado! Tente fazer o seguinte: mova o seu repositório para um diretório que não tenha espaços (veja que no caminho do seu repositório tem o **"Program Files"**, que contém um espaço).

Depois atualize o `remote` do seu projeto para o novo diretório. Me deixe saber se isso resolve o seu problema :)

**Comment by lucasmedrado** [comment]
@fdaciuk Professor alterei a pasta, porém o erro continua

'C:/cygwin64/Git/home/lucas/my-project.git' does not appear to be a git r
epository
fatal: Could not read from remote repository.

**Comment by fdaciuk** [comment]
Bom, o windows tem algumas particularidades, vamos tentar algumas outras coisas:
Tente trocar no seu remote as barras. Ao invés de barras normais, use 2 barras invertidas. O caminho deve ficar assim:

```
C:\\cygwin64\\Git\\home\\lucas\\my-project.git
```

Me diga se, alterando seu remote para esse caminho, funciona :)

**Comment by lucasmedrado** [comment]
@fdaciuk Olá Professor, o problema foi resolvido. A solução foi deixar de utilizar o cygwin. Eu utilizo o vscode, a partir disso desinstalei o git e instalei novamente e nas configurações do git eu configurei ele para utilizar o prompt do windows, deu certo. Agora estou utilizando o prompt do vscode. Professor gostaria de agradecer pela atenção e pela rapidez em me responder, obrigado. Até mais.

**Comment by fdaciuk** [comment]
Legal @lucasmedrado, que bom que resolveu :)
Uma recomendação que tive de terminal para windows foi o [Hyper](https://hyper.is). Parece funcionar bem no windows.

Como já ouvi também que o terminal do vscode buga às vezes, é legal ter algum outro de backup :)

Mas que bom que deu tudo certo! Qualquer coisa, fique à vontade para perguntar :)
