### ISSUE TITLE
Seção 8 aula 44 -> Trabalhando em equipe no Github parte 2

### ISSUE THREAD

**Issue by lucasmedrado** [da2k/curso-git-e-github-ninja#46]
@fdaciuk 
Olá professor, gostaria de tirar uma dúvida. Professor nessa 44 da seção 8 vc ensinou sobre o fetch, ou seja, uma forma de ter o projeto atualizado, porém gostaria de saber qual a diferença entre o fetch e o pull request. Se, quando eu tiver trabalhando em equipe e em vez de usar o comando fetch, eu utilizar o pull request, teria algum problema? Se sim, qual seria?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @lucasmedrado! Pode fazer sim, sem problemas. Um _Pull Request_ nada mais é que uma feature do GitHub, que vai fazer a utilização do **git fetch + git merge** (e algumas outras coisas) por baixo dos panos :)

**Comment by fdaciuk** [comment]
Oi @lucasmedrado! Vou fechar a issue, mas fique à vontade para perguntar sempre que tiver dúvidas, ok? :)
