### ISSUE TITLE
Diferença entre git fetch e git pull

### ISSUE THREAD

**Issue by lucasmedrado** [da2k/curso-git-e-github-ninja#47]
Olá professor, gostaria de tirar uma dúvida. Professor nessa 44 da seção 8 vc ensinou sobre o fetch,

 ou seja, uma forma de ter o projeto atualizado, porém gostaria de saber qual a diferença entre o 

fetch e o pull request. Se, quando eu tiver trabalhando em equipe e em vez de usar o comando 

fetch, eu utilizar o pull request, teria algum problema? Se sim, qual seria?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @lucasmedrado! Respondi sua dúvida na issue #46 =)
