### ISSUE TITLE
[Aula 11] uso do vim no cygwin

### ISSUE THREAD

**Issue by helder-rangel** [da2k/curso-git-e-github-ninja#48]
Oi Daciuk,
Adoro o Vim, mas só posso usar Windows 10, com Cygwin. Qual a saída para usar o Vim no Cygwin?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @helder-rangel! Você pode instalar o NeoVim, que é uma versão melhorada, e ainda abre em janela, sem precisar, necessariamente, abrir pelo terminal :)

**Comment by fdaciuk** [comment]
Oi @helder-rangel! Vou fechar a issue, mas fique à vontade para perguntar sempre que tiver dúvidas, ok? :)
