### ISSUE TITLE
[Seção 3] [Aula 15]  - Evitar que uma branch seja mergeada

### ISSUE THREAD

**Issue by MatheusAriel** [da2k/curso-git-e-github-ninja#49]
@fdaciuk , existe algum comando que ao criar uma branch, eu "bloqueio" para que ela nunca seja mergeada por outra branch? **(como nesse exemplo da aula, para q a branch site não seja mergeada com a branch dev)**

**Comment by fdaciuk** [comment]
Oi @MatheusAriel! No git especificamente não. Mas no GitHub, você pode definir algumas configurações de segurança, como por exemplo, impedir merges "manuais" na master =)
