### ISSUE TITLE
Duvida aula semana [2]

### ISSUE THREAD

**Issue by andersoonweb** [da2k/curso-git-e-github-ninja#5]
Essa dúvida não tem muito haver com o assunto, mas fiquei interessado em saber... você roda o npm sem o sudo várias vezes e em tempos diferente, é alguma configuração que provê isso ai ?

@fdaciuk

**Comment by fdaciuk** [comment]
Para instalação de pacotes locais, normalmente não é necessário o sudo. Nem deveria ser, na real. Se para instalar pacotes com `--save` ou `--save-dev` você precisa usar sudo, significa que as permissões do seu diretório `~/.npm` estão erradas.

Mude o dono desse diretório com o comando:

``` sh
sudo chown -R $(whoami):$(whoami) ~/.npm 
```

Isso deve resolver o problema ;)
