### ISSUE TITLE
[Seção 3] [Aula 18] Erro ao fazer pull

### ISSUE THREAD

**Issue by MatheusAriel** [da2k/curso-git-e-github-ninja#50]
@fdaciuk  ao fazer o pull na pasta de um usuário do time, surgiu o erro:

**fatal: refusing to merge unrelated histories**

Após pesquisar, vi para fazer o seguinte comando:

**git pull origin master --allow-unrelated-histories**

Deu certo, mas gostaria de saber o por que do erro, e quais são esses parâmetros após o master (allow-unrelated-histories)

**Comment by fdaciuk** [comment]
Oi @MatheusAriel! Esse erro acontece quando você tenta fazer merge de duas branches que não têm relação uma com a outra: ou são projetos git diferentes, ou você pode ter criado a branch com o parâmetro `--orphan`.

Ou seja: se as branches não têm histórico relacionado, você vai obter esse erro. O correto não é usar o `--allow-unrelated-histories` (que vai "forçar" o merge), mas sim analisar o porquê você recebeu esse erro.

Na maior parte das vezes que isso acontece, ou você não deveria fazer o merge das duas branches, ou você deveria criar uma nova branch, com base naquela que você estava tentando fazer o merge, para manter o histórico correto dos commits :)
