### ISSUE TITLE
não consigo fazer o merge das alterações no githu como um colaborador, aula 8 episódio 2

### ISSUE THREAD

**Issue by Magnothiago** [da2k/curso-git-e-github-ninja#51]
$ git merge upstream/master
fatal: refusing to merge unrelated histories

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Magnothiago! Esse erro acontece porque você está tentando fazer merge de dois repositórios diferentes. Veja que na aula, os dois repositórios são relacionados. Um é uma "cópia" do outro (fork). E a cópia que está no "upstream" (repositório do usuário `@daciuk`) contém alguns commits a mais do que o repostiório da `@anamariabraga`.

Mas eles têm o mesmo histórico, por isso o merge funciona corretamente.
No seu caso, você pode ter tentado usar um outro repositório qualquer, que não tem o mesmo histórico do que você está tentando fazer o merge, por isso esse erro é exibido :)

**Comment by Magnothiago** [comment]
Você tem os slides dos comandos que foi usado nas aulas?

Em dom., 29 de mar. de 2020 às 05:55, Fernando Daciuk <
notifications@github.com> escreveu:

**Comment by fdaciuk** [comment]
Tenho sim! Me manda uma mensagem lá pela Udemy com o seu e-mail que eu te envio os slides :)
De preferência, um e-mail que tenha acesso ao Google Drive :)
