### ISSUE TITLE
Erro ao executar o comando para instalar o gulp. Seção.2 Aula.8

### ISSUE THREAD

**Issue by jeanKarpinski** [da2k/curso-git-e-github-ninja#52]
Não estou conseguindo instalar o gulp local, o que estou fazendo de errado ? vlw

```
$ npm i --save-dev gulp
bash: npm: command not found

```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jeancrk! O erro diz que `npm` não foi encontrado.. isso significa que você não instalou o Node.js :)

**Comment by fdaciuk** [comment]
Oi @jeancrk! Vou fechar a issue, mas fique à vontade para perguntar sempre que tiver dúvidas, ok? :)
