### ISSUE TITLE
Muita demora ao executar : GIT PULL/PUSH ORIGIN "nome-da-branch"

### ISSUE THREAD

**Issue by douglas-88** [da2k/curso-git-e-github-ninja#53]
Bom dia professor,

Queria lhe pedir uma ajuda com algo que tenho passado há alguns dias quando vou fazer um GIT PULL/PUSH ORIGIN MASTER(ou qualquer outra branch) para os meus repositórios no Bitbucket, fica demorando um tempão... , tipo uns 40 min .
Mas eu consigo fazer, há momentos que consigo rapidamente, mas tem acontecido com frequencia de demora muito...
![Captura de tela de 2020-04-15 09-13-23](https://user-images.githubusercontent.com/10869960/79336502-3daea180-7efa-11ea-9dce-174df35b2f3c.png)

**Comment by fdaciuk** [comment]
Oi @douglas-88! Isso pode ser duas coisas: ou alguma instabilidade no Bitbucket, ou sua conexão com a internet :)

Obs.: Desculpe a demora na resposta, como você não me marcou (com `@fdaciuk`), acabei não recebendo a notificação da issue criada. Sempre que criar uma issue, pode me marcar, que eu vou responder o quanto antes, ok? :)

**Comment by douglas-88** [comment]
Boa tarde professor @fdaciuk , imaginei isso, mas tava acontecendo direto, mas parou de acontecer. kk.
Obrigado pelo retorno.
Vejo muitos bons comentários com relação ao seu curso de Javascript ninja na UDEMY, só que analisando a grade do curso, o Javascript abordado é o antigo, o ES5, caso adquira você ainda dá suporte a esse curso , quanto aos desafios que há nele ?
E você pretende lançar esse mesmo curso atualizado , já com as novidades do ES6 ainda em 2020 ?

**Comment by fdaciuk** [comment]
Sim, dou suporte para todos os meus cursos :)

As pessoas têm um pensamento errado quando se fala de ES5: ES5 não é JavaScript "antigo". ES5 é a base da liguagem.

Toda nova feature que entrou na liguagem, foi pensada para funcionar **em cima** do ES5.

Nada do ES5 foi (e nunca será) perdido, pois todas as novas features devem ser "retrocompatíveis", ou seja: sites que já existem, e usam apenas ES5, não podem quebrar. Essa é uma das premissas do JavaScript: **não quebrar a web!**

Por isso o curso continua válido, e vai continuar te dando toda a base necessária que você precisa para aprender a linguagem, inclusive para aprender as novidades que entraram na liguagem à partir do ES6 :)

Futuramente eu pretendo fazer um curso mostrando todas as novidades da linguagem, onde o JS Ninja vai ser a base para os novos :)
