### ISSUE TITLE
Renomear arquivos e manter versionamento

### ISSUE THREAD

**Issue by rafael-marques** [da2k/curso-git-e-github-ninja#54]
No caso, quando preciso renomear um arquivo que está no repositório, o git entende que eu apaguei um arquivo e criei outro. Porém eu gostaria de renomear um arquivo mas fazer o git entender que aquele é o mesmo arquivo que venho utilizando, alterando e versionando mas que apenas mudou de nome. Isso é possível?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rafael-marques! Quando você faz um `git add` dos dois arquivos juntos - o "novo", que na verdade foi renomeado, e o "deletado" - o `git` já vai entender que ele foi somente renomeado =)

**Comment by fdaciuk** [comment]
Logo ao fazer o `git add` dos dois, ao rodar um `git status`, você vai ver que a linha referente a esse arquivo vai ficar algo como:

```
renamed:    nome-anterior -> nome-novo
```

**Comment by fdaciuk** [comment]
Oi @rafael-marques! Vou fechar a issue, mas fique à vontade para perguntar sempre que tiver dúvidas, ok? :)
