### ISSUE TITLE
Liberação de Release

### ISSUE THREAD

**Issue by Marranjal** [da2k/curso-git-e-github-ninja#55]
Olá Daciuk. Fiz o curso e achei muito bom, mas tenho uma dúvida em relação a liberação de release, acho que não explicaste esta parte. 
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Marranjal! Que bom que curtiu :)
Qual a dúvida? :)

**Comment by Marranjal** [comment]
Oi @fdaciuk a minha duvida é como disponibilizar um release.

**Comment by fdaciuk** [comment]
Você quer dizer, aqui pelo GitHub? Se for isso, é só ir na aba "Releases", na página inicial do seu repositório, e criar uma nova Release com a versão mais recente do seu projeto :)

Era isso que você queria saber?

**Comment by Marranjal** [comment]
Ok obrigado.
@fdaciuk

**Comment by fdaciuk** [comment]
Legal! Qualquer coisa, só avisar :)
