### ISSUE TITLE
[Aula 01]

### ISSUE THREAD

**Issue by figortabosa** [da2k/curso-git-e-github-ninja#56]
Professor não entendi como os comados que você fez no git criaram os arquivos no Sublime, fiz os comandos mas não aparece nada pra mim no sublime

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @figortabosa! A quais comandos você se refere?

**Comment by figortabosa** [comment]
Professor quando você deu o comando de git add apareceu o símbolo de “+” no seu projeto no sublime no meu não aparece.
Tenho que configurar alguma coisa no meu sublime?

Enviado do meu iPhone

Em 18 de jun de 2020, à(s) 13:06, Fernando Daciuk <notifications@github.com> escreveu:

**Comment by fdaciuk** [comment]
Ah entendi.. provavelmente era algum plugin de git para o Sublime :)
Não sei te dizer exatamente o nome, pois hoje já não uso mais o Sublime, mas se procurar por algum plugin de git pra ele, você vai encontrar :D

**Comment by figortabosa** [comment]
Desculpa Professor eu não entendi muito bem eu Devo baixar algum plugin?
Quero dar continuidade no curso mas as alterações que eu faço no projeto
não são vistas no Git.
O que vc me indica eu fazer?
obrigado por responder minhas duvidas!


Em sex., 19 de jun. de 2020 às 13:04, Fernando Daciuk <
notifications@github.com> escreveu:

**Comment by fdaciuk** [comment]
O plugin do Sublime não vai afetar seu aprendizado do Git no curso. Se quiser instalar o plugin de git no seu sublime, será só um "plus", ok? :)

Ou seja: siga com o curso e não se preocupe com plugins :)

**Comment by eguadorodrigo** [comment]
@figortabosa Fala cara, beleza? um plugin ajuda muito na questão visual de acompanhamento do que está sendo feito no teu ambiente, mas pode ser feito com ou sem o uso deles. Se te referes a plugins como este https://www.sublimetext.com/docs/3/git_integration.html
Podes encontrar tantos outros como o GitaHead, GitKraken e outros, mas em miúdos todos usam os mesmos comandos.
Boa sorte e bons estudos!

**Comment by fdaciuk** [comment]
Oi @figortabosa! Vou fechar essa issue, mas se ainda tiver dúvidas, pode comentar aqui que eu vou te ajudando, ok? :)
