### ISSUE TITLE
[Aula 1] Dúvida sobre GIT add

### ISSUE THREAD

**Issue by tlrmail** [da2k/curso-git-e-github-ninja#57]
@fdaciuk

**Comment by tlrmail** [comment]
Issue de teste

**Comment by fdaciuk** [comment]
@tlrmail ainda está com dúvida? :)

**Comment by tlrmail** [comment]
estou gostando do curso, mas ainda estou praticando pra fixar o conhecimento. Obrigado!

**Comment by fdaciuk** [comment]
Legal! Qualquer coisa, fique à vontade para perguntar :)
