### ISSUE TITLE
[Section 3][Aula 15]  Não consigo eliminar os ficheiros do branch site com git rm -rf .

### ISSUE THREAD

**Issue by RS-coding** [da2k/curso-git-e-github-ninja#58]
Estou na parte da aula que criamos uma nova branch vazia -->     **git checkout --orphan site**

Depois você diz que todos os arquivos existentes saiem do estado  git repository  e passam para a staging area.
E que temos duas opções:  reutilizar esses arquivos ou simplesmente remover.

Depois  você  faz  -->   **git rm -rf .** 
para remover os arquivos todos.

Mas eu já tentei várias vezes fazer isso e de outras formas , como removendo um a um  e não funciona. Dá me uma mensagem de erro: 
 **fatal pathspec  '.' dit not match any files** 

Eu uso o Cmder como terminal e ele tem alguns  comandos do linux também. Não entendo porque isto não funciona.
Depois tento eliminar o branch vazio criado mas ele não me permite eliminar nem volta atrás.
Pode me ajudar?

Obrigada

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RS-coding! O problema provavelmente foi que o windows não reconheceu o `.` como o caminho do diretório atual. Tem algumas formas de resolver isso:

- Você pode deletar os arquivos um a um, passando o nome deles, com:

```
git rm -rf index.html
git rm -rf style.css
```

E assim por diante.

Se estiver usando o windows 10:
- Você pode tentar usar o Powershell como terminal, que tem mais suporte para comandos do Linux;
- Ou o caminho mais recomendado para esses casos: você pode instalar o usar o WSL2, que vai te permitir rodar um terminal do Linux mesmo, aí você ter o melhor dos dois mundos: pode continuar usando windows sem problemas, e quando precisar do terminal, vai ter um Linux disponível, com tudo o que você usaria se estivesse usando o Linux nativamente :)

**Comment by RS-coding** [comment]
A questão é que eu já experimentei também remover um a um e dá me o mesmo erro com o nome do arquivo. depois tento eliminar a nova branch para tentar  fazer tudo de novo e não me permite .

Em relação ao WSL2 poderia me enviar um link  onde contenha a instalação.Procurei na net e não encontrei.

**Comment by fdaciuk** [comment]
Que estranho! Consegue me mandar um print do resultado do comando `git status` pra eu ver?
Sobre o WSL2, pode seguir esse [tutorial aqui](https://docs.microsoft.com/en-us/windows/wsl/install-win10) :)

**Comment by RS-coding** [comment]
![git status 2](https://user-images.githubusercontent.com/40272091/105754533-7f20b280-5f4a-11eb-9817-7141153d707b.jpg)
![git status](https://user-images.githubusercontent.com/40272091/105754540-8051df80-5f4a-11eb-8241-6c89d77024e5.jpg)
envio  o  print  do git status e rm -rf . e rm -rf index.html
Não consigo mesmo entender porque não funciona

Em relação ao tutorial muito obrigada! :)

**Comment by fdaciuk** [comment]
Show! Bom, na verdade já deu certo o que você queria fazer! Tá vendo ali que os arquivos aparecem logo abaixo de "Untracked files"? Significa que eles não estão mais na _staging area_, eles agora nem foram adicionados nela (com `git add <arquivo>`), por isso você não consegue remover com `git rm` :)

Mas você vai conseguir remover eles com os comandos do seu terminal mesmo, usando `rm -rf .` (só cuidado com o caminho: digitando `.`, o caminho é o seu diretório atual. Se colocar uma barra na frente, você vai acabar deletando arquivos desde a raiz do seu sistema, então muito cuidado com esse comando, ok?)

Tenta aí e me diz se deu certo!

:)

**Comment by RS-coding** [comment]
Desculpe Fernando , não entendi o que era para fazer agora. 

> Mas você vai conseguir remover eles com os comandos do seu terminal mesmo, usando rm -rf . (só cuidado com o caminho: digitando ., o caminho é o seu diretório atual. Se colocar uma barra na frente, você vai acabar deletando arquivos desde a raiz do seu sistema, então muito cuidado com esse comando, ok?) Tenta aí e me diz se deu certo!

Eu já fiz o  _rm -rf   ._ e deu aquele erro. 
Tenho que fazer um add . ? e depois fazer um rm -rf  .? Não entendi mesmo o que tenho de fazer  agora.

**Comment by fdaciuk** [comment]
Se você usar o comando `rm -rf <nome_do_arquivo>` não deleta? Consegue me mandar um print pra eu ver o erro?

**Comment by fdaciuk** [comment]
De qualquer forma, você pode deletar pelo windows explorer mesmo (interface visual), se achar mais fácil, ok? :)

**Comment by RS-coding** [comment]
Sim eu enviei o print screen disso. Dá erro
![git status 2](https://user-images.githubusercontent.com/40272091/105768980-6ec60300-5f5d-11eb-968c-2f44532dab45.jpg)

deletar pelo windows explorer como assim?  Fiquei agora confusa. O site é um branch  orphane atraves do dev e como voce explicou podemos remover os arquivos ou fazer commit. eu tentei remover com rm -rf .  e da me aquele erro que eu mostrei e ao fazer o git status aparece na mesma la os ficheiros como untracked. Mas no video voce faz isso e nao dã erro  nenhum e  voce faz git status e despararecem todos os ficheiros menos o node-modules que voce remove a seguir .

**Comment by fdaciuk** [comment]
@RS-coding está dando erro porque você está tentando remover usando o `git`. O que eu tinha comentado é pra usar o `rm` sem o `git` na frente, por isso pedi um print, pois esse comando deveria funcionar. O comando que você precisa usar é:

```
rm -rf .
```

Sem o `git` na frente do `rm` :)

O "deletar pelo windows" eu quis dizer pela listagem de arquivos do windows mesmo, o windows explorer. Sabe onde você acessa o C:, "Meu computador", etc? Onde você visualiza seus arquivos e pastas? Era por ali que eu estava me referindo :)

**Comment by RS-coding** [comment]
ah já entendi! desculpe a falha minha.
Obrigada pela ajuda :)

**Comment by fdaciuk** [comment]
Sem problemas! Conte comigo sempre que precisar :)
