### ISSUE TITLE
[Seccao 03][Aula #18] Não consigo fazer o git pull origin master no segundo colaborador  -Ana

### ISSUE THREAD

**Issue by RS-coding** [da2k/curso-git-e-github-ninja#59]
Olá Fernando, 
estou com um problema  no exercicio Team, que  é criado varios ficheiros : Servidor Raquel Andre Minerva Ana.
Consegui clonar , até ai tudo bem.
Criei um ficheiro no Colaborador Raquel - **index.html** fiz os passo do git add e git commit e fiz no final o _**git push origin master**_ . Até aqui tudo ok .
Criei  um ficheiro css no Colaborador Ana - **css/style.css** fiz novamente os passos do git add e commit . Depois ao fazer o **_git pull origin master_** d dá me um erro que nao entendo .  Já confirmei os passos anteriores novamente para me certificar se não tinha cometido algum erro e está tudo bem. Não entendo.  Envio o print screen: 
![git pull origin master](https://user-images.githubusercontent.com/40272091/106320248-e2745280-6272-11eb-997e-b70331bf4a91.jpg)

Obrigada !

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RS-coding! Desde a versão 2.9 do git, ele não permite mais fazer merge quando o histórico do repositório não bate com o histórico do seu projeto.

E ele faz isso por questões de segurança: pode ter algum caso, por exemplo, de alguém que conseguiu acesso ao seu repositório de alguma forma ilícita, e injetou algum código malicioso ali.

No caso dos exemplos do curso, não é isso que acontece, então temos certeza que podemos fazer _merge_ sem nos preocupar com esse problema. 

Nesse caso, para funcionar o `git pull`, você só precisa então passar um argumento `--allow-unrelated-histories`, para dizer ao git que você confia nesse código e permite o merge. O comando ficaria assim:

```
git pull origin master --allow-unrelated-histories
```

Me deixe saber se funcionou :)

**Comment by RS-coding** [comment]
Agora dá me este erro : 

![novo erro](https://user-images.githubusercontent.com/40272091/106384783-e9af7380-63cc-11eb-9e8b-ce5a5d902863.jpg)

**Comment by fdaciuk** [comment]
Certo, parece que deu tudo certo, só que o git não conseguiu abrir seu editor para definir a mensagem de merge. Você só precisa fazer o commit desse merge agora, colocando uma mensagem, que já deve funcionar :)

**Comment by RS-coding** [comment]
Já entendi. obrigada!

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :)
