### ISSUE TITLE
Clonando repositorios

### ISSUE THREAD

**Issue by andersoonweb** [da2k/curso-git-e-github-ninja#6]
Na aula 18, você mostra uma simulação de trabalho em equipe com quatro usuários, mas apenas dois ativos(Ana e Fernando). Existe uma pasta, que é o servidor, onde há uma pasta interna de pré nome ecommerce, nessa pasta existe o material do git init.

Apos, você configura o caminho do remote no computador do Fernando, vai configurar o dar Ana de uma forma mais rápido, clonando o repositório principal as "informações" aparecem na pasta.

A duvida é o seguinte, porque as informações aparecem após a clonagem ? A pasta .git ou o conteúdo que lá o tem se encaminha de guardar todas essas informações?  E onde fica armazenadas, qual pasta? qual arquivo ?

Pergunta meio boba, mas fiquei curioso para saber. E também isso seria o mesmo lance em um servidor online, como amazon, digital ocean, heroku dentro outros...

**Comment by fdaciuk** [comment]
@andersonweb quando vocẽ usa o `git clone`, é como se vocẽ fizesse manualmente os seguintes passos, dentro do diretório do seu projeto:

``` sh
git init
git remote add origin <endereço-do-repositório-no-servidor>
git fetch
git pull
```

O `git clone` faz esses passos automaticamente, além criar um novo diretório com o nome do seu projeto :)

Mais informações: https://git-scm.com/docs/git-clone

**Comment by fdaciuk** [comment]
Ah, sobre o servidor: sim, mesmo esquema. A ideia era mostrar como se estivesse em um servidor mesmo. Se você quiser deixar um repositório na amazon, digital ocean, ou onde você quiser, você pode.

A vantagem de usar um serviço como GitHub ou Bitbucket pra isso é que eles tem algumas ferramentas úteis, como issues, pull requests, wiki, pages, diff visual online, etc. :)

**Comment by fdaciuk** [comment]
E sim, tudo o que você faz através dos comandos que começam com `git`, e que precisa ser armazenado, fica armazenado no diretório `.git`, dentro do seu projeto ;)

**Comment by andersoonweb** [comment]
Show!!! Só recomenda algum servidor online pra dar uma brincada ?! Um que você já conheça bem. Valeu :dancer: ! @fdaciuk

**Comment by fdaciuk** [comment]
Na verdade, não recomendo fazer isso manualmente. É importante saber como criar um repositório, e como ele funciona, mas com as ferramentas que temos hoje, não faz sentido você manter um repositório manualmente. A não ser que tenha planos de fazer um SaaS com ele :)

Até porque, para "dar uma brincada" você vai ter que pagar de qualquer forma xD

Se ainda assim quiser fazer, recomendo a AWS, onde você pode ter uma conta free por 1 ano, e testar os serviços deles. Pode usar o EC2 pra testar o que precisa lá ;)

**Comment by andersoonweb** [comment]
A ferramenta que você fala, já vem juntamente com o servidor ?

**Comment by fdaciuk** [comment]
As ferramentas que temos hoje são GitHub e Bitbucket, entre outros. ;)

**Comment by andersoonweb** [comment]
Mas no caso desses servidores, temos que fazer na mão ? Ou á ferramentas similares ao Github ?
