### ISSUE TITLE
Como formatar no terminal  para que apareça a branch com que estamos a trabalhar ?

### ISSUE THREAD

**Issue by RS-coding** [da2k/curso-git-e-github-ninja#60]
Oi Fernando,
me desculpe a pergunta . Mas eu gostaria de saber o que  é preciso fazer para ter a mesma configuração que você tem no seu terminal a mostrar entre parenteses a branch em que você está. Assim:
![Untitled-1](https://user-images.githubusercontent.com/40272091/107118788-5326fa80-6883-11eb-8774-beed02433842.jpg)

É que é muito mais prático e não corro o risco de cometer tantos erros. Eu estou usando o terminal virtual Linux (Unbuto) no Windows. 

Muito obrigada!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RS-coding! Eu uso o `zsh` como meu shell principal, e a extensão [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh), que tem alguns temas bem legais, inclusive esse que eu usei no curso :)

No link da documentação do oh-my-zsh tem todas as instruções para instalar o zsh, depois o oh-my-zsh, e como definir um tema para o seu terminal :)

Hoje eu uso um tema diferente: uso o Avit, [com algumas modificações](https://github.com/fdaciuk/avit-da2k). 

Mas você pode escolher o que mais te agradar :)

**Comment by kasokinho** [comment]
Digite no terminal: nano ./bash-rc

cole esse código no final da linha.
```
parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

export PS1="\u@\h \[\e[32m\]\w \[\e[91m\]\$(parse_git_branch)\[\e[00m\]$ "
```
assim, você configura o bash para mostrar a branch seguida do diretorio.

**Comment by RS-coding** [comment]
Obrigada @fdaciuk e @kasokinho pelas dicas. vou experimentar.

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar :)
