### ISSUE TITLE
Dúvida sobre a chave https

### ISSUE THREAD

**Issue by facuri** [da2k/curso-git-e-github-ninja#62]
Fernando tudo bem?
Queria tirar uma dúvida se possível,
quando tento fazer um git remote ou um git clone usando a chave https
dá o seguinte erro: erro: fatal: Unable to find remote helper for 'https' 
O que poderia ser?
Meu sistema operacional é o Windows 7 e eu uso o git bash.
Obrigado.
Manoel Dalmo
 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @facuri! Tudo certo, e vc?
Consegue mandar um print do seu terminal, mostrando o comando que você está rodando, e essa mensagem de erro? Só pra eu entender melhor o contexto do que você está tentando fazer :)

**Comment by facuri** [comment]
Fernando tudo bem?
Fernando fiz os prints mas como 
eu te envio pelo github?
Obrigado.
Manoel Dalmo.

 fdaciuk

**Comment by fdaciuk** [comment]
Oi @facuri ! Só arrastar a imagem e soltar aqui onde você escreve a mensagem, que o GitHub já faz upload automaticamente :)

Ao fazer isso, você vai ver que uma URL vai ser gerada aqui na caixa de textos, onde você escreve a mensagem. Para confirmar se a imagem veio certa, é só clicar na aba "Preview" aqui na caixa de mensagens mesmo, que fica ao lado da aba "Write" :)

Para voltar a escrever a mensagem, só clicar em "Write" novamente! :)

**Comment by facuri** [comment]
!Fernando, estou-lhe enviando os prints
Obrigado.
Manoel Dalmo
 
![gitclone](https://user-images.githubusercontent.com/29820825/116960693-8e18ae80-ac77-11eb-914c-bd5a21a9546a.png)
![gitremote](https://user-images.githubusercontent.com/29820825/116960709-996bda00-ac77-11eb-8267-8bfb0b39b871.png)

fdaciuk

**Comment by fdaciuk** [comment]
Legal @facuri! Pesquisando sobre esse erro aqui, descobri que possivelmente é um problema de configuração do git no windows. O problema pode estar em vários lugares, então vou te recomendar algumas possíveis soluções:

A primeira é tentar reinstalar o git. Pode ser que, na hora da instalação, tenha ficado algum pacote de fora, ou o programa não teve permissão suficiente para setar as variáveis de ambiente necessárias para o git funcionar.

A segunda opção - um pouco mais trabalhosa, mas mais vantajosa ao meu ver - seria instalar o WSL2.
Com o WSL2, você terá acesso a um terminal Linux dentro do seu windows, e isso vem com todas as vantagens de usar um Linux - já que essas ferramentas de linha de comando normalmente são pensadas incialmente para funcionar no Linux - mas com a vantagem de você continuar usando o SO que tem mais familiaridade (no seu caso, o Windows).

Se quiser tentar a primeira opção antes, já que é mais simples, fique à vontade! Se funcionar, tudo bem, você pode seguir sem problemas. Mas o WSL2 vai acabar te trazendo vantagens, para quando você precisar usar outras ferramentas de linha de comando, além do git.

É um trabalho inicial maior que vai compensar depois :)

Me deixe saber o que você decidiu fazer, e se deu tudo certo! Se tiver qualquer dúvida, fique à vontade para mandar aqui, que vou te ajudando a resolver, ok? :)

**Comment by facuri** [comment]
Fernando, tudo bem?
Fernando primeiro te agradecer pela dicas do gitbash que você me deu,
eu instalei o meu novamente e agora a chave https está funcionando normalmente, valeu.
Sobre a aula 18. Clonando repositorios, quando eu estou trabalhando em um projeto em equipe
e eu estou comitando a minha parte antes de fazer o git push eu devo sempre fazer o git pull
isso evitaria conflitos com alguma outra atualização de alguém da equipe no repositorio principal? 
está certo?
Obrigado
Manoel Dalmo
fdaciuk

**Comment by fdaciuk** [comment]
Isso mesmo @facuri! `git pull` sempre antes de fazer o `push` =)
Na verdade, pra evitar conflitos, faça `git pull` sempre antes de começar a trabalhar no repositório =)

**Comment by facuri** [comment]
Fernando, tudo bem?
Fernando na aula 20 auto merge,
na hora em que eu fiz o merge da master dentro da feature dev
o meu git bash deu uma mensagem que eu não consegui entender
eu fiz o print se você puder me ajudar ficaria grato.
Obrigado
Manoel Dalmo.
![print_merge](https://user-images.githubusercontent.com/29820825/119205162-daccf980-ba6d-11eb-939e-90fb6f0480eb.png)

fdaciuk

**Comment by fdaciuk** [comment]
Oi @facuri! Essa é a tela do vim, para você escrever uma mensagem de commit. Ela vai ser aberta sempre que um merge acontecer com sucesso! Você só precisa escrever uma nova mensagem de commit, ou deixar essa mensgem mesmo =)

Para salvar e sair, é só digitar `ZZ` (dois `z` maiusculos) =)

**Comment by facuri** [comment]
Fernando, valeu  muito obrigado.
Manoel
fdaciuk

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar =)
