### ISSUE TITLE
Duvida na aula 11 curso git/github

### ISSUE THREAD

**Issue by jeffonis** [da2k/curso-git-e-github-ninja#63]
boa tarde prof, estou com duvida na aula 11 do curso de git/github ninja, na configuração do editor de texto que o senhor utiliza, no caso o meu não tem aquela configuração...
no caso seria por conta que eu uso windows e o senhor utiliza linux? (segue imagem abaixo de todas as minhas configs, acho que com elas fica mais facil de entender algo)

![imagem_2021-07-14_135820](https://user-images.githubusercontent.com/62406460/125662371-335f5fdb-d835-4ceb-81e0-3cc62d7b2aff.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jeffonis! Na verdade é só porque você ainda não definiu essa configuração. Você pode usar o comando mostrado na aula para definir seu editor de preferência =)

**Comment by jeffonis** [comment]
mas como faço o download de um editor? 
@fdaciuk

**Comment by fdaciuk** [comment]
Você não usa nenhum editor de códigos hoje? Se não tem nenhum de preferência, recomendo o VS Code, dá uma olhada:
https://code.visualstudio.com/
