### ISSUE TITLE
aula 17, duvida

### ISSUE THREAD

**Issue by jeffonis** [da2k/curso-git-e-github-ninja#64]
bom dia!
me surgiu uma duvida na aula 17 do curso de git github, como visto na imagem abaixo, eu criei o repositorio e afins, mas ele esta dando esse erro, não sei o que poderia ser, o senhor poderia me ajudar, por favor ? 

![image](https://user-images.githubusercontent.com/62406460/126498560-a158f4a4-564e-48c6-98aa-97ce8d99558d.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jeffonis! Você rodou o `git init --bare` no diretório `my-project.git`?

**Comment by jeffonis** [comment]
sim sim @fdaciuk 

ele me deu essa mensagem 
![image](https://user-images.githubusercontent.com/62406460/126562776-e55fe28d-b17c-47d3-845f-3f65dc163dcd.png)

**Comment by fdaciuk** [comment]
Boa! Tenta colocar como url do remote essa que apareceu aí, que tem o `cygwin64` no caminho, possivelmente é isso que está acontecendo =)

Se por acaso ainda assim não funcionar, minha recomendação seria você instalar o WSL2 no windows, pra conseguir usar um terminal do Linux.. aí você não vai ter essas inconsistências que são específicas do windows =)

**Comment by jeffonis** [comment]
@fdaciuk esta acontecendo isso ... 
![image](https://user-images.githubusercontent.com/62406460/126575254-7978bafa-f695-4269-8d4c-dff4c75213cb.png)

**Comment by fdaciuk** [comment]
@jeffonis o problema parece ser de resolução de caminhos do windows mesmo :\

Nesse caso, recomendo você instalar o WSL2 mesmo, que aí você vai conseguir fazer tudo pelo terminal do Ubuntu, e não deve ter essas inconsistências =)

**Comment by jeffonis** [comment]
@fdaciuk obrigado pela atenção <3 

se não for pedir demais, teria algum tutorial para fazer isso? não conheço wsl2 :/

**Comment by fdaciuk** [comment]
Claro meu caro! No próprio site da microsoft você encontra:
https://docs.microsoft.com/en-us/windows/wsl/install-win10
