### ISSUE TITLE
aula 26 curso git/github

### ISSUE THREAD

**Issue by jeffonis** [da2k/curso-git-e-github-ninja#65]
@fdaciuk boa tarde! 
estou na aula 26 do curso de git/github, mas estou tendo esse problema 
![image](https://user-images.githubusercontent.com/62406460/127550629-392351ce-649d-47be-a4a4-a9bd221534be.png)
o sr saberia o que pode ser?

**Comment by fdaciuk** [comment]
Oi @jeffonis! Como você ainda não tem adicionado o remote `origin`, você não consegue editar a url dele.. primeiro você precisa definir o origin com `git remote add origin <endereço-do-repo>`

Aí sim, ao rodar o `git remote -v` você vai ver o `origin` definido. Só então você consegue alterar a url dele, com o `set-url` =)

Deu pra entender o problema? =)

**Comment by jeffonis** [comment]
@fdaciuk consegui! é que tinha um repo com o mesmo nome, ai tive problemas por conta disso, ai eu apaguei e criei esse como o senhor falou, agora consegui! obrigado!

**Comment by fdaciuk** [comment]
Boa! Qualquer dúvida, só avisar :D
