### ISSUE TITLE
aula 31

### ISSUE THREAD

**Issue by jeffonis** [da2k/curso-git-e-github-ninja#66]
boa tarde, prof
desculpe o incomodo, estou na aula 31 do curso de git github e me surgiu uma duvida, gostaria de saber por que acontece esse erro quando eu coloco o git push origin master, quando coloquei só o git push subiu pro repositorio no git hub...
![image](https://user-images.githubusercontent.com/62406460/128234099-bbd53d34-0441-440b-9fc5-d3038bd4c393.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jeffonis! Se você olhar a última linha da mensagem onde você executou o `git push`, vai perceber que o nome da sua branch não é `master`, e sim `main` =)

Essa foi uma alteração recente do GitHub: todo repositório novo, criado pela interface do GitHub, vai ter a branch `main` como padrão, ao invés da `master` =)

Por isso, ao tentar executar `git push origin master` você recebe esse erro. O comando correto, para o seu caso, é:

```
git push origin main
```

**Comment by jeffonis** [comment]
aaaahhh tem razão @fdaciuk, muito obrigado! eu tentei outras formas aqui e num tinha ido, muito obrigado <3

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar :D
