### ISSUE TITLE
Erro de pull na aula 18

### ISSUE THREAD

**Issue by system-neto** [da2k/curso-git-e-github-ninja#67]
Olá Fernando tudo Bem?! Na aula 18 o meu ambiente esta apresentando um erro na hora do pull da Ana !!
![Captura_do_erro_no_pull_git_sincronizacao](https://user-images.githubusercontent.com/74797032/135731290-903e8594-2533-4b7c-a27b-9c8b073314e3.PNG)

o mesmo ocorre no usuário Fernando
![pull_do_fernando](https://user-images.githubusercontent.com/74797032/135731376-d809b3c3-2a9d-41b5-88b7-963316bb254a.PNG)
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pinheiro-neto! As versões mais novas do git pedem pra você configurar a forma que você quer fazer o `pull`: se com `rebase` ou com `merge`. Recomendo usar com `rebase`.

Pra fazer isso, você só precisa rodar esse comando, que vai definir essa configuração de forma global, para todos os seus projetos que estiverem usando git:

```
git config --global pull.rebase true
```

Aí pode tentar fazer o `pull` que vai funcionar como esperado ;)

**Comment by system-neto** [comment]
Obrigado professor! Acabei de atualizar e ficou tudo certo

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar :D
