### ISSUE TITLE
comando LL no cmd do  windows

### ISSUE THREAD

**Issue by manuelamador27** [da2k/curso-git-e-github-ninja#68]
@fdaciuk estou usando o cmd do windows no curso de git, e o comando LL e LS nao funcionam, qual os ocmandos q substituem?
posso usar o cmd ou é melhor usar o terminal q vc sugeriu?
meu sistema é windows 10, nao vou trabalhar co linux

**Comment by fdaciuk** [comment]
Oi @manuelamador27! No windows, recomendo você usar o WSL2, pois ele vai te dar um terminal linux pra você usar dentro do windows :D 

Se não for possível usar o WSL2, dê uma olhada nesse link para aprender os comandos básicos para o cmd do windows:
https://tutorial.djangogirls.org/pt/intro_to_command_line/
