### ISSUE TITLE
Browse files

### ISSUE THREAD

**Issue by andersoonweb** [da2k/curso-git-e-github-ninja#7]
O browse files deveria mostrar quais arquivos foram alteradores no commit especifico, certo ?
Testei aqui e ele retorna todos os arquivos. E  lógico, o arquivo commit foi modificado apenas alguns arquivos apenas.

Qual seria a solução, deverá fazer alguma configuração que você esqueceu ? xD

**Comment by fdaciuk** [comment]
@andersonweb, tá falando de qual parte do curso?

**Comment by andersoonweb** [comment]
Semana cinco! na aula 26, a partir do minuto: 08:47 @fdaciuk

**Comment by fdaciuk** [comment]
Ah, vi aqui. Se ele está mostrando todos, os arquivos, pode ser 2 coisas:
1. Ou você commitou todos os arquivos nesse commit;
2. ou você não está no link do commit, e sim na listagem de arquivos.

Cola aqui o link que você está testando que eu vejo :)

**Comment by andersoonweb** [comment]
Esse link [aqui](https://github.com/free-time/freetime-cli/commit/978006ee099bff0be38a774ba2f9b45951921230)

**Comment by fdaciuk** [comment]
Certo.. preciso ver no seu terminal como está.. pode me mandar uns prints?

**Comment by andersoonweb** [comment]
Como assim ?! Essa ferramenta não é própria do Github ?

**Comment by fdaciuk** [comment]
Agora entendi o que você quis dizer :)
Ficou entendido então?

Browser files vai mostrar todos os arquivos **daquele commit específico**.

Para ver cada arquivo por si só, você precisa clicar no botão "View", ou clicar no ícone de "expand", que fica na lateral do arquivo, onde aparece os números das linhas :)
