### ISSUE TITLE
Apagando tudo que está na branch

### ISSUE THREAD

**Issue by andersoonweb** [da2k/curso-git-e-github-ninja#8]
Para criar uma nova branch sem commit algum, já foi ensinado: 

<code>git checkout --orphan nome-da-branch</code>.

Simulando uma situação: 

Eu tenho uma branch que se chama <b>exemplo1</b> e uma outra <b>exemplo2</b>. A <b>exemplo2</b> foi criada a partir da <b>exemplo1</b>, logo contém tudo.
Caso eu queria apagar TUDO que tem numa branch, todos os commits como eu faria ? Deixando a branch LISA. 

Isso é possível?

**Comment by fdaciuk** [comment]
@andersonweb usando o `--orphan`, a nova branch é criada sem nenhum log, mas os arquivos físicos continuam ali. Se você criou a branch `exemplo2`, com `-b` dentro da `exemplo1`, então a `exemplo2` vai ter todo o histórico da `exemplo1`. Agora, a partir dessa você pode criar uma nova com `--orphan`, que todos os arquivos estarão lá, mas o histórico estará em branco ;)

Não sei se respondi sua pegunta :)

**Comment by andersoonweb** [comment]
Respondeu sim! valeu
@fdaciuk

**Comment by andersonweb** [comment]
@fdaciuk

**Comment by fdaciuk** [comment]
:dancer:
