### ISSUE TITLE
Git attributes

### ISSUE THREAD

**Issue by andersoonweb** [da2k/curso-git-e-github-ninja#9]
Não foi citado no curso, mas vejo em diversos repositórios o <code>.gitattributes</code>. Basicamente e de uma maneira simples, pra que ele serve. @fdaciuk

**Comment by fdaciuk** [comment]
@andersonweb de forma bem resumida, ele serve para dizer ao Git o "tipo" que aquele arquivo deve ser tratado.

Os sistemas operacionais podem tratar arquivos que não são conhecidos de forma diferente. Tipo: uma **dll** no Windows é um arquivo binário, mas no Mac ou Linux, ele poderia ler esse arquivo como um arquivo de texto, e tentar fazer um _diff_ de forma textual. Com o `.gitattributes` você pode setar esse tipo de arquivo como binário, e então o git vai saber, independente do sistema, que ele não deve fazer essa diferenciação :)

Mais sobre o `.gitattributes` aqui: https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes
